### ISSUE TITLE
Triple kill kai wet pommel

### ISSUE THREAD

**Issue by LABWAZHERE** [schofida/CWORR#102]
![20230514104333_1](https://github.com/schofida/CWORR/assets/128126252/cd232f6e-a315-44e7-924e-82eae5ca7e08)
![20230514104346_1](https://github.com/schofida/CWORR/assets/128126252/50a91e7e-65a1-4e74-8d5a-3d08e284078b)
![20230514104446_1](https://github.com/schofida/CWORR/assets/128126252/6030f451-9d8b-438f-9695-244e0ed9b0e5)

**Comment by LABWAZHERE** [comment]
mcm
![20230514104757_1](https://github.com/schofida/CWORR/assets/128126252/3918243b-6bb4-443c-8107-c3290dede273)

**Comment by LABWAZHERE** [comment]
![20230514104848_1](https://github.com/schofida/CWORR/assets/128126252/d8b59877-c708-4a6f-ac1d-5f6e49069746)

**Comment by LABWAZHERE** [comment]
UPDATE; IT HAPPENED A THIRD TIME
the missions i got were:
Kill Kai
Sabotage mill
Kill Kai
Rescue from fort Kastav
Kill Kai
Defence of Fort Kastav

**Comment by Eve-Knight** [comment]
Tangentially, that dialogue in the screenshot should use "sow" rather than "sew."

**Comment by LABWAZHERE** [comment]
Thirdly, this only happens with Kai

**Comment by schofida** [comment]
Each time you got CWMission05 (Kill Kai) was he already dead?

At this point I think this is a Skyrim engine bug. So CWMission05 takes the enemy Field CO and fills into a Reference Alias. I then have the options checked to ensure that the Enemy Field CO is alive and that the this Field CO is a required alias. So in short, if the enemy field co is already dead, this Alias should not be filled and ergo, this quest should not be given. But it all doesn't work. Nothing in this f@#$ engine ever works! !@#$!@#%$$@#%#$%

**Comment by LABWAZHERE** [comment]
he was dead after the first one, each time I got it again he was dead but I revived him and killed him again each time

**Comment by schofida** [comment]
Upload https://github.com/schofida/CWORR/releases/tag/v1.0.13a which should hopefully prevent the quest from starting if the enemy field co is dead going forward. I added yet another check to ensure that the Field CO is DEFINITELY NOT DEAD...

**Comment by LABWAZHERE** [comment]
Reapers list update:
Added deathS list
Death should properly read through his list of dead people and no longer register dead people as alive
