### ISSUE TITLE
Hadvar starts too far away in rescue from fort kastav

### ISSUE THREAD

**Issue by LABWAZHERE** [schofida/CWORR#103]
after freeing prisoners i think hadvar and the other troops should be a bit closer to the fort than where they start
![20230514105557_1](https://github.com/schofida/CWORR/assets/128126252/346b807f-b26e-40f1-b13b-487c69aac3bc)

**Comment by LABWAZHERE** [comment]
also he goes here for some reason
![20230514105853_1](https://github.com/schofida/CWORR/assets/128126252/69a24837-5722-4e66-9862-1a806c8d16cb)

**Comment by schofida** [comment]
I tried to set them closer but it won't work. They ending up getting too close to the fort and will start fighting the troops while you are trying to sneak in.

**Comment by LABWAZHERE** [comment]
Damn that sucks
