### ISSUE TITLE
Battle of fort Kastav/Rescue from Fort Kastav complications

### ISSUE THREAD

**Issue by LABWAZHERE** [schofida/CWORR#104]
Battle of Fort Kastav needs to be given after Rescue from Fort Kastav

Rescue from Fort Kastav and Battle of Fort Kastav should be swapped on second Winterhold offensive it should be Rescue from fort Kastav on the first Regain Winterhold but on second Regain Winterhold after losing it, it should be Battle for Fort Kastav.

the reason i say this is Hadvars line after the mission he says "he'll set up a garrison here"  

Additionally when Battle for Fort Kastav is given it should be renamed to Defence of Fort Kastav, because after Rescue it becomes an imperial fort. As such this occurs
![20230514111140_1](https://github.com/schofida/CWORR/assets/128126252/27f30f7d-433e-4fc7-8e84-d067ebe28cb7)

**Comment by LABWAZHERE** [comment]
Additionally visa versa for rescue from fort neugard and battle/Defence of fort neugard

**Comment by schofida** [comment]
> Additionally when Battle for Fort Kastav is given it should be renamed to Defence of Fort Kastav, because after Rescue it becomes an imperial fort. As such this occurs

This should be fixed now in v1.014a. Rescue from Fort Kastav should now prevent 'Battle of Fort Kastav' from starting in the first attack of Winterhold Hold campaign. Note that if you lose Winterhold Siege and try to take Winterhold again later, Battle of Fort Kastav should fire at that point.

> Rescue from Fort Kastav and Battle of Fort Kastav should be swapped on second Winterhold offensive it should be Rescue from fort Kastav on the first Regain Winterhold but on second Regain Winterhold after losing it, it should be Battle for Fort Kastav.

I'm not too sure about this. Once you start Rescue from Fort Kastav on your first offense of Winterhold, before you sneak in, Hadvar gives something along the lines of 'I guess Tulius wants to bolster our troops before the siege of Eastmarch' or something like that. I think it makes sense to me that Fort Kastav is just another Stormcloak fort that happened to be housing Imperial prisoners. I personally think that this is just another way of taking over a fort. I don't think that this and 'Battle for Fort Kastav' should be in the same campaign.

Note: when I say campaign, I mean, everything from Tulllius/Ulfric telling you where to go next until the siege for the city in that particular hold.

**Comment by LABWAZHERE** [comment]
Yep that I agree with, I forgot about that line Hadvar says (was too focused on taking the fort)

**Comment by LABWAZHERE** [comment]
I also do support the idea that the vanilla quest missions should only work once (you can’t make the same mistake twice)

**Comment by LABWAZHERE** [comment]
But on that note I do have a question, do story missions work if you switch sides? And should they still be given or since you’ve technically already completed them should they not be given?

**Comment by schofida** [comment]
If you have done the story missions before switching sides, they won't work. CW quest (the main overarching quest that is running throughout your playthrough until you finish the battle for Solitude/Windhelm) keeps track of them. I think its ok if you don't get them again once you switched sides. There is not much difference between doing the Imperial or Stormcloak versions of them.

**Comment by LABWAZHERE** [comment]
this was on a non switching sides save
