### ISSUE TITLE
Stormcloak Rogue needs to be removed or race changed/Stormcloak scout issues

### ISSUE THREAD

**Issue by LABWAZHERE** [schofida/CWORR#105]
Note: Full disclosure i am on level 100
Stormcloak rogue is an Argornian, this would never happen
![20230514111618_1](https://github.com/schofida/CWORR/assets/128126252/cee0aea9-34fc-4a0f-864a-3dc4bf819f28)
![20230514113358_1](https://github.com/schofida/CWORR/assets/128126252/5ec21610-a0e3-4f90-95c5-2af30bf09867)
Human rogue that sometimes appears:
![20230514120148_1](https://github.com/schofida/CWORR/assets/128126252/96f495f0-7bf1-446c-a538-4ccb0ec4ec45)

Additionally i have seen this cursed abomination from time to time (Stormcloak scout)
![20230514113916_1](https://github.com/schofida/CWORR/assets/128126252/72ee6c96-afb2-4c3f-ba19-a6f876994670)

**Comment by schofida** [comment]
Handling under #51
