### ISSUE TITLE
Reporting for Duty for fort Amol isn't appearing

### ISSUE THREAD

**Issue by LABWAZHERE** [schofida/CWORR#108]
Rikke doesn't have reporting for duty dialogue ONLY FOR EASTMARCH
mcm menu
![20230514122153_1](https://github.com/schofida/CWORR/assets/128126252/cfa08108-9bbf-49e7-a160-6777eabe4dba)

**Comment by schofida** [comment]
Should be fixed in v1.0.12a (hopefully). I forgot to revert the 'Generic' Fort dialogue conditions. Hopefully that should fix it (and not break anything else).

**Comment by LABWAZHERE** [comment]
I’ll test this when I get home
