### ISSUE TITLE
Battle of Falkreath ??????????????????

### ISSUE THREAD

**Issue by LABWAZHERE** [schofida/CWORR#112]
![20230515201726_1](https://github.com/schofida/CWORR/assets/128126252/02b5755a-1add-4d31-b8fa-ca40dc5ee102)
this was after changing defence troop mults to its lowest setting and killing a few stormcloaks after losing all my troops, didn't fail mission until i fast traveled away
![20230515201726_1](https://github.com/schofida/CWORR/assets/128126252/0e35cbff-6067-44f8-9923-03b56e975af6)
forgot to get mcm shot sorry

**Comment by LABWAZHERE** [comment]
no mod conflicts, battle went fine but after all friendly troops were dead and we had 0% it didn't auto complete and i killed a few stormcloaks and that occured, troop multipliers were edited so that might be a contributer

**Comment by ds-nscorp** [comment]
Sorry I forgot about that. I have tested this in a minor city before but I'll check to see what happens when the troops are set very low.

**Comment by schofida** [comment]
Looking at this next

**Comment by schofida** [comment]
This should be fixed now https://github.com/schofida/CWORR/releases/tag/v1.0.15a I think that if the troop pool was set below the threshold to display objective things go wonky. Now to sets to a set number to keep the troop pool from dipping too low.
