### ISSUE TITLE
Fort neugard quest not being given (with Fort commanders mod)

### ISSUE THREAD

**Issue by LABWAZHERE** [schofida/CWORR#113]
![20230515205745_1](https://github.com/schofida/CWORR/assets/128126252/8f3c9ec2-ff2c-492b-850c-8be223da6b47)
it also before this said setting up siege

**Comment by LABWAZHERE** [comment]
mcm
![20230515205939_1](https://github.com/schofida/CWORR/assets/128126252/af217a4c-ea49-4eca-ad40-9c0c6bd3155e)

**Comment by schofida** [comment]
So Fort sieges are starting fine for me even with the mod so I will close this. But do note that I have added an experimental CW mission path during campaigns before the city siege. Now 4 missions per campaign will be default. The vanilla missions will happen first if able. A combination of 2 of the six new quests will then start. And then finally the fort siege. Give it a try and let me know what you think (or if it all just doesn't work lol)
