### ISSUE TITLE
Battle for Whiterun v1.0.13a Notes

### ISSUE THREAD

**Issue by Eve-Knight** [schofida/CWORR#114]
During the exterior battle, I was spammed with notifications that various targets were too powerful for Hysteria. I was not using this spell directly. I was not using a weapon with this enchantment. I suspect one of the NPCs fighting in the battle had such a weapon, though. I further suspect that the effect was being erroneously attributed to me rather than them.

Most likely due to the same issue, I also received a significant amount of Illusion skill increase. I was not actually using any such skills, but it increased at an extremely high rate during the battle.

After lowering the drawbridge, I know it's vanilla behavior for the defenders to run into the city. This always seemed really weird, though. They make no effort to defend themselves from the attackers. It would make more sense for them to just keep fighting, at least if they are being attacked.

The portion in the streets of Whiterun seemed to go well.

Dragonsreach seemed fine up till defeating Balgruuf. Then it got slightly weird.

I use JK's Dragonsreach, so the extra obstacle in front of the throne seemed to cause some oddity for the scene where Vignar shows up. He did some awkward walking around the throne room before ultimately stopping way behind Balgruuf (instead of in front of him, since they're talking to each other). I also had three people and a pet skeever following me, so it's possible he had trouble pathing there even without the interior layout change.

The vanilla issue of the combat/siege music continuing even after the fighting is over persists. As usual, it thankfully goes away after I exit Dragonsreach AND fast travel to report the victory to the faction leader.

Before I could exit Dragonsreach, though, Galmar forced a conversation start with me. He didn't actually say anything, though. And he didn't have any new options. So that also seemed odd.

**Comment by Eve-Knight** [comment]
Oh, also, before actually entering the city gates, I noticed Galmar ended up in combat with my followers. Probably a stray ranged attack from one of them or something. Probably also a vanilla issue. But noting anyway.

**Comment by LABWAZHERE** [comment]
>Before I could exit Dragonsreach, though, Galmar forced a conversation start with me. He didn't actually say anything, though. And he didn't have any new options. So that also seemed odd.


This happens post Riften battle for imperials Rikke with strike up a convo with you before you exit Mistviel but will get shy and not say anything and I think it happens post Markarth but I can’t remember

**Comment by schofida** [comment]
> During the exterior battle, I was spammed with notifications that various targets were too powerful for Hysteria. I was not using this spell directly. I was not using a weapon with this enchantment. I suspect one of the NPCs fighting in the battle had such a weapon, though. I further suspect that the effect was being erroneously attributed to me rather than them.

Thanks for reporting. I will investigate this.

> Before I could exit Dragonsreach, though, Galmar forced a conversation start with me. He didn't actually say anything, though. And he didn't have any new options. So that also seemed odd.

I will look at this as well. I never liked this.

**Comment by schofida** [comment]
This half fixed.... https://github.com/schofida/CWORR/releases/tag/v1.0.15a

> Before I could exit Dragonsreach, though, Galmar forced a conversation start with me. He didn't actually say anything, though. And he didn't have any new options. So that also seemed odd.

This should not happen anymore

**Comment by schofida** [comment]
> During the exterior battle, I was spammed with notifications that various targets were too powerful for Hysteria. I was not using this spell directly. I was not using a weapon with this enchantment. I suspect one of the NPCs fighting in the battle had such a weapon, though. I further suspect that the effect was being erroneously attributed to me rather than them.

This should be fixed now as well.
