### ISSUE TITLE
False front for Dawnstar/Morthal questions/clarification 

### ISSUE THREAD

**Issue by LABWAZHERE** [schofida/CWORR#115]
So how rare is false front, how often is it meant to be given cause I haven’t gotten it for Dawnstar yet like at all

That’s the mission with the courier and delivering false documents to Dawnstar or Riften’s CO 

 I get compelling tribute but not as frequently as I seem to get rescue from fort____ fairly frequently so just asking about false front

**Comment by LABWAZHERE** [comment]
Additionally I don’t seem to get compelling tribute for Riften, at least not on first campaign I did get it for Markarth with the Stormcloaks at one point but Riften seems less frequent (when I go back to earlier saves)

**Comment by schofida** [comment]
It's all luck of the draw right now. Every quest (if it can start) has an equal chance of starting. After release I might try something to force the vanilla quests first and then the new CWO added quests and finally the Fort siege before the Captial.

**Comment by schofida** [comment]
You should get it pretty reliably now :)
