### ISSUE TITLE
Reach Stormcloak Camp Quartermaster Acts Like Player Trespasses

### ISSUE THREAD

**Issue by Eve-Knight** [schofida/CWORR#116]
Despite being a Stormcloak sent to the camp, the quartermaster says "I'm warning you. Back off." And then "This is your last warning. Get away from there or else."

She also does not open the trade interface when attempting to interact with her.

I then get a "That's it. Don't say I didn't warn you."

It seemed limited to her close proximity, though. I was able to walk away from her and into the rest of the camp without her following or attacking.

**Comment by LABWAZHERE** [comment]
Wait are quartermasters base game?

**Comment by LABWAZHERE** [comment]
I thought I downloaded an OCW enchantments box set mod during my Xbox days and I think one of the mods was either adding quarter master or making him sell things or something

**Comment by Eve-Knight** [comment]
Yes, they're base game. I've seen a mod that gives them a normal dialogue menu so you actually pick an option to ask them what they have to sell. I'm not using it, though. Vanilla behavior is for them to be there and just open the trade window when you talk to them.

**Comment by LABWAZHERE** [comment]
Ah I see

**Comment by Eve-Knight** [comment]
Upon my return, other soldiers in the camp exhibited similar behavior. After I got my reward from the leader, though, they seemed to stop.

**Comment by Eve-Knight** [comment]
Ah. They stopped because my followers killed one of them. Definitely an issue.

**Comment by LABWAZHERE** [comment]
Yeah the followers have a few issues even when using OCW

**Comment by Eve-Knight** [comment]
Hm. Maybe they're the ones viewed as trespassing.

**Comment by schofida** [comment]
It could be a follower issue. This has never happened to me. Does it happen without the follower?

**Comment by LABWAZHERE** [comment]
It could ha an issue with a multiple followers mod

**Comment by Eve-Knight** [comment]
Didn't try without follower. I don't have a mod specifically for multiple followers, but I do have followers from mods that serve as additional followers.

**Comment by schofida** [comment]
I will make a note of this and close for now. civil war even without mods has always been very problematic with followers
