### ISSUE TITLE
Civil war champions question from nexus

### ISSUE THREAD

**Issue by LABWAZHERE** [schofida/CWORR#118]
User asked

“Wish there's a Creation Club option/patch of making Civil War champions into their CC armor instead of vanilla armor in this mod. The CC Champions Quest can co-exist with the Civil War, just need the Civil War champions to wear those armors during the conflict.”

**Comment by LABWAZHERE** [comment]
Full disclosure I am keeping some people in the loop on the nexus page, and answering questions about the version currently available on nexus, if it is a bug I am sure hasn’t been patched or if someone suggests things I forward it to you

I am sorry if this makes you upset

**Comment by schofida** [comment]
This is definitely on my TODO list. I like the Imperial Champions but the one with Ebony armor can use a makeover. https://trello.com/c/MjS3CMwk/44-support-for-cc-content
