### ISSUE TITLE
seasons unending betrayal/ seasons unending quest not even starting

### ISSUE THREAD

**Issue by LABWAZHERE** [schofida/CWORR#12]
is the ability to switch sides during seasons unending being preserved? if so, on the old mod version ulfric couldn't be killed on the imperials side when you betrayed him during seasons unending and switched to the imperials and sometimes the truce would break.

also ran into an issue in this version where as stormcloak i can't activate seasons unending after taking falkreath, (imperials still had markath and thus it still should have triggered) reloaded prior save (i got it to work before taking Morthal) and after taking Morthal it still didn't work, i don't think taking morthal triggers it. i haven't tested this with imperials but i am guess a similar result may occur.

also
after finally getting it to work, i am a stormcloak and i sided with tulius at every choice (they only have markath so we traded for riften and i refused to make them pay for reparations) ulfric never said the "you swore an oath of loyalty to the stormcloaks, do you remember that?" line, i still received an Elven sword from tulius. after walking out i said to him "reporting for duty" and he says we are in a truce right now" and now after beating dragonslayer i can not restart the civil war, i talked to galmar i said reporting for duty, he says he is busy ulfric doesn't even have any lines, waited 24 hours and fast traveled and no courier or anything.

i am not a coder or anything, i just wanted to bring this to your attention as i didn't know where else to go to report bugs

this is a new play through btw without the old version

**Comment by schofida** [comment]
Thank you very much for this report. I will take a look. I regrettably never made it far enough in the main quest to start Season Unending and until now I was unaware that you can even do this quest while the Civil War is underway. I do not change anything about this quest but I imagine CWO can unfortunately interfere with things.

I do know that I cut "you swore an oath of loyalty to the stormcloaks, do you remember that?" because if you lose Markarth naturally during the war, he would say that when trying to take Markarth back which did not make much sense. But I will try to add that back and there might be a way to determine that holds were given up during Season Unending.

The rest of your issues, I am not sure and would need to perform further investigation. If you can, can you provide a screen shot of the CWO Debugger MCM screen?

Additionally, I don't know if you have papyrus logging turned on (its an INI setting) but if you have it turned on, there should a logs folder next to the same folder in your documents where your saves are stored. If you have that folder, can you provide me those logs as well?

You said that the quest did not start after taking Falkreath but then you said that you did get it to start? What did you do?

From the UESP page, it looks like the quest starts after 'The Fallen' sub-quest in the main quest. And I think the quest finally activates when speaking with the Jarl of Whiterun. Did you expect something to happen after taking Falkreath?

**Comment by LABWAZHERE** [comment]
the seasons unending quest is about the civil and having a truce to capture odahviing so it can't start if the main quest is complete or if the civil war is complete. it starts so long as 2 holds are held by the enemy (i.e battle of Solitude or battle of Windhelm hasn't started) however on a not so relevant note i believe ocw restores the cut part where you can do it with only Solitude or Windhelm left and they request a minor hold but i don't remember it has been a while since i did that, but might still be a good idea if it is possible to restore if it was in the original cwo

So after taking Falkreath it should have started after talking to grey mane, and the fallen quest is unable to be continued and seasons unending starts. for seasons unending, he should have said "i can't while the imperials could attack me at my door step" but he didn't, instead he just said "so how do we spring this trap?" even after failing speech checks. i will add i reloaded an old save and i can  do the truce after the battle of Whiterun, but not after Morthal, ill try and cheese it so Morthal isnt the second hold that i need to conquer, it could just be a Morthal and Winterhold issue due to them being the last ones you take before the capitals with the Stormcloaks and imperials respectively.

to get it to work i had to reload a save before battle of Morthal and did not actually pursue the peace until after taking Falkreath and it all ran as normal, chose Elwen to stay, Markath traded for Riften, denounced that a massacre happened ya know the usual. 
 only thing that didn't work was when the outcome was heavily favouring the empire galmar saying "For what it's worth, I'm sorry to see you go. You fought well for us." and general tulius responding with "Don't listen to him. Ulfric's been telling lies about himself for so long, he's actually starting to believe them." did not appear however i still received an elven sword from Tulius. 
as these lines are uncut in the base game.

in cwor you can actually switch sides at this point and change from stormcloak to imperials, and this is not happening as of current,
if you do re add this, make sure you make Ulfric killable as he was not in the original mod. and make sure the final scene takes place properly and tulius and rikke don't just teleport to Ulfric and Galmor, and visa versa. if you want i can go more in depth about this specific bug of this part of the quest if you do add the truce in, ill test it and give you the verdict.


as for the rest........

i don't know how to use papyrus , and i will check the cwo debugger mcm menu.

love the mod but as i have explained below i really hope you can get the truce and betrayal to work 

the main reason i chose this mod is because this mod has the ability to take a Stormcloak Whiterun as the imperials (i play as imperials and lose all holds then take them all back to make Ulfric think he has won, then a reckoning occurs (it makes for a better song)) and the truce not working and the betrayal also not working is really a bummer for me, don't get me wrong i like this mod as it offers more than ocw but it would suck if the truce and betrayal don't end up working.

love the work, hopefully you can make this mod fully stable when compared to the original cwo 
i love it when people are fixing bethesdas game for them, if you can't get the betrayal to work, that is fine ill just have to settle with an imperial only game

**Comment by LABWAZHERE** [comment]
![20230318091156_1](https://user-images.githubusercontent.com/128126252/226062372-abd4d54d-9b4d-4ff7-acee-1385cd96dc2f.jpg)


is this what you mean by the debugger? or is there a separate thing? btw in this save instead of Falkreath it is Markarth that Ulfric wants me to take after Morthal


also on another non seasons unending related note

This visual glitch:
![20230318104502_1](https://user-images.githubusercontent.com/128126252/226070551-2ae39987-c288-47b8-b4ca-959cb68baccc.jpg)
bar can't be moved unless you use arrow keys because of it and it only goes up in multiples of 2 so i cant do just 1 or 3 or 5 like at all. also can't change it from 3 even if i move it

**Comment by ds-nscorp** [comment]
Thank you. Yes that is it. I will take a look. And thank you for showing me that MCM bug. Hopefully I can have season quest fixed by this weekend. I will let you know. Thanks again!

**Comment by schofida** [comment]
And in regards to whether I can get the betrayal working, I found where the Skyrim developers removed the code to switch sides. I will certainly try to get it to work!

**Comment by LABWAZHERE** [comment]
That's great news, i found another bug, the dawnstar general doesn't appear (imperial side)
![20230318184505_1](https://user-images.githubusercontent.com/128126252/226092822-a0696a57-522a-41af-ba7d-42ec00ccf03a.jpg)
![20230318184825_1](https://user-images.githubusercontent.com/128126252/226092825-08175227-c1c9-46c0-898a-fdb6e9762687.jpg)
![20230318184829_1](https://user-images.githubusercontent.com/128126252/226092827-9a431dae-6fb5-4df9-a80b-7eefc9776246.jpg)

**Comment by LABWAZHERE** [comment]
Can't wait, let me know when they are done, I want to be the first to test it (You don't have to obey that request, if there is a more competent bug tester, use them. I am just enjoying playing this mod)

**Comment by LABWAZHERE** [comment]
> Thank you. Yes that is it. I will take a look. And thank you for showing me that MCM bug. Hopefully I can have season quest fixed by this weekend. I will let you know. Thanks again!

it is important to note that the old cwor had an issue where the truce could be broken if a defence quest was set up, so make sure it pauses all of them to prevent rouge sieges starting the war back up again

another thing to note is originally bethesda intended the quest to work with just Windhelm or solitude remaining, and they would just request a minor hold instead of a major one

**Comment by ds-nscorp** [comment]
Hello, I think I got the betrayal functionality working. I haven't tested yet but I found why the quest wasn't starting and how to switch the sides. I am testing some other stuff first but I should be posting a new version soon I hope.

**Comment by LABWAZHERE** [comment]
> I should be posting a new version soon I hope.

Will I need a new save for it?

**Comment by ds-nscorp** [comment]
You won't 😀

**Comment by LABWAZHERE** [comment]
:D

**Comment by ds-nscorp** [comment]
Hello, just keeping you updated. I have been testing the defense campaigns and something is definitely wrong which I think snowballs into some of the other issues you have found. This issue is hard to pin down but I will hopefully get to the bottom of it soon.

**Comment by LABWAZHERE** [comment]
goodluck, hope you can pin it down

**Comment by schofida** [comment]
@LABWAZHERE So I am unable to test this since I don't have any saves anywhere near this in the main quest. But I did adjust the conditions to remove the Morthal/Winterhold conditions. And I did add the functionality to switch sides. I posted a new version in the Release section.

**Comment by LABWAZHERE** [comment]
testing now, i apologise for the wait, i am Australian so there is a bit of a time difference

**Comment by LABWAZHERE** [comment]
@schofida i have noticed the mcm bug with the quests is still broken.

**Comment by LABWAZHERE** [comment]
okay so, seasons unending still will not activate, i tried a save post battle of markarth (second last hold, so solitude was last one)
, pre markarth nothing. ill try pre morthal and post battle of whiterun but i have a theory that they won't work, it may have something to to with grey mane or the game not registering the civil war being active. but ill have to test that when i do a stormcloak play through for the most part grey manes dumb face just looks at me and says sure lets capture a dragon. i may also have to completely delete conquest from my game but i don't think this is a conquest issue.

**Comment by schofida** [comment]
> okay so, seasons unending still will not activate, i tried a save post battle of markarth (second last hold, so solitude was last one), pre markarth nothing. ill try pre morthal and post battle of whiterun but i have a theory that they won't work, it may have something to to with grey mane or the game not registering the civil war being active. but ill have to test that when i do a stormcloak play through for the most part grey manes dumb face just looks at me and says sure lets capture a dragon. i may also have to completely delete conquest from my game but i don't think this is a conquest issue.

Ok I will check again. I found Grey Mane's dumb dialog tree :) but I did remove the Morthal and Winterhold conditions. I will see if anything else is blocking it.

> @schofida i have noticed the mcm bug with the quests is still broken.

Can you send me a screenshot of the debug? Where are you and what are you trying to do via the MCM?

**Comment by schofida** [comment]
Also, can you open the console and let me know the results when you type the following commands?

getstage CW
getstagedone CW 30

**Comment by LABWAZHERE** [comment]
okay update, i haven't done what you asked yet cause i just saw it but i have some updates to that 1st IT WORKS, YOU SHOULD HAVE SEEN THE LOOK ON ULFRICS FACE WHEN I BETRAYED HIM 2nd to get this to work i had to activate seasons ending with jarl baller before battle of whiterun. after the battle of whiterun (i did not talk to ulfric) using the mcm to switch hold sides, (markarth and falkreath) it gave me that same issue i was talking about. i couldn't progress, had to force unstuck the quest and then instead of being take liberate morthal it was liberate falkreath

**Comment by LABWAZHERE** [comment]
> > 
> 
> Can you send me a screenshot of the debug? Where are you and what are you trying to do via the MCM?

campaign phase thing, still won't work, that's what i meant

**Comment by LABWAZHERE** [comment]
> Also, can you open the console and let me know the results when you type the following commands?
> 
> getstage CW getstagedone CW 30

get stage 12.00, get stage done, 0.00, nothing happened

**Comment by LABWAZHERE** [comment]
couple of other things, concurrent sieges still occured
![20230401111344_1](https://user-images.githubusercontent.com/128126252/229261049-eb53f8c1-d151-4561-9bad-935e4818fe2c.jpg)
This happened (dancing objective marker)
![20230401111412_2](https://user-images.githubusercontent.com/128126252/229261063-f173c608-9006-4d89-9830-a1fb5a658d49.jpg)
![20230401111413_1](https://user-images.githubusercontent.com/128126252/229261064-c9e7cc2d-77c0-423b-8124-fb30cdadbcf2.jpg)
![20230401111413_2](https://user-images.githubusercontent.com/128126252/229261057-30dfdf20-438b-4905-8bfe-f3c786691dfb.jpg)
![20230401111412_1](https://user-images.githubusercontent.com/128126252/229261062-fb988f20-03ca-4e3c-a840-d2cd47704c58.jpg)

**Comment by schofida** [comment]
Hey, I moved some of your comments to other issues to keep this organized. I'd look to keep this issue focused on Season Unending quest.

I posted another update to the releases file. I think I finally found the Dialog tree that starts (or doesn't start) Season Unending. Can you try in that save again Post Morthal?

**Comment by LABWAZHERE** [comment]
yes will do now, also i have updates to other things like solitudes last stand so please also check those as well

**Comment by schofida** [comment]
Oh and don't apologize about the time difference and delays in testing. Your reports have already been a huge help. I am also unfortunately really busy with stuff so I only get maybe an hour or so a night to look at this so you will most likely be waiting on me :(

**Comment by LABWAZHERE** [comment]
don't worry about you being busy it is called life. i will not be available for a week from the 6th so i won't be able to test things until the 13th

**Comment by LABWAZHERE** [comment]
> I posted another update to the releases file. I think I finally found the Dialog tree that starts (or doesn't start) Season Unending. Can you try in that save again Post Morthal?

IT WORKS! ill try with just solitude as the last remaining hold as well. (as i still had markarth in this save)

**Comment by LABWAZHERE** [comment]
update: all works, with solitude as the last hold, meaning it will work with Winterhold and Windhelm, the only thing missing is tulius is meant to give you a reward for betraying ulfric and visa versa (i think, i remember the first one before i brought up the issues with seasons unending) he gave me an elven sword the first time pre update, idk if that is normal however. and this isn't a big deal. 


feels good to finally close this issue.

**Comment by LABWAZHERE** [comment]
actually i'll leave it open until you give the verdict on the elven sword (isn't a big deal)

**Comment by LABWAZHERE** [comment]
as celebration here is ulfric and vignar being flung off of a cliff (they deserve it after the pain you've been through with this truce)
![20230401132022_1](https://user-images.githubusercontent.com/128126252/229265656-d697c86b-cf84-401d-9001-f1458c443a3d.jpg)
![20230401132037_1](https://user-images.githubusercontent.com/128126252/229265680-c24c5159-be41-43d8-86ba-63336a55c104.jpg)
