### ISSUE TITLE
Whiterun exterior troops spawns

### ISSUE THREAD

**Issue by LABWAZHERE** [schofida/CWORR#120]
So someone on nexus mentioned the fact that they failed the battle of Whiterun 3 times because 

The Stormcloak troops started spawning on the lever at the lever to the lower bridge once the defend the drawbridge objective was reached

their question was

Is the stormcloaks supposed to have teleporting soldiers/giants during battle of Whiterun?

now 

I have a question relating to that, since the only way to the drawbridge is via the ramp behind the archer towers, 

Does the stormcloak path finding take them there or do they just spawn in up there?

**Comment by Eve-Knight** [comment]
If their pathfinding is trying to take them there but it's blocked because something is in the way, I think it's normal for them to teleport instead.

**Comment by LABWAZHERE** [comment]
> them to teleport

The issue they are asking about is actually one I have encountered before which is why I play mostly on god mode, I think after a certain amount of time one spawns in to trigger the next stage.

**Comment by LABWAZHERE** [comment]
> 

What I was asking is does the path finding of the Stormcloaks take them up the ramp and to the upper part?

**Comment by Eve-Knight** [comment]
I think it does when I'm attacking. No idea about when the player defends Whiterun.

**Comment by LABWAZHERE** [comment]
> I think it does when I'm attacking. No idea about when the player defends Whiterun.

As someone who has extensive experience in battle cheese, I can assure you this happens on defence, 
I’ll be minding my own business,  killing Ulfrics boys then suddenly out of nowhere the drawbridge drops

(I intentionally lose the battle of Whiterun a lot to trigger the defence scenario)

**Comment by schofida** [comment]
> What I was asking is does the path finding of the Stormcloaks take them up the ramp and to the upper part?

Yes path finding takes troops up the ramp. Most troops just fight but 2 of them are programmed to go after the objective.

> If their pathfinding is trying to take them there but it's blocked because something is in the way, I think it's normal for them to teleport instead.

This is also true. There are invisible markers at each of the siege phases (there are 5 from attack scene with field co to the final objective being between before the troops run in). As troops are killed, depending on the phase, the troop would be reset at one of these invisible markers. I will check to see if there are any of these markers right next to the bridge. This happened in vanilla but none of the troops were programmed to pull the lever so I guess no-one ever noticed.

**Comment by schofida** [comment]
So I verified that the respawn markers all spawn at around the front gate where the barricade is. But they will pathfind all the way to the second gate lever. Best strategy is to field the choke point and make sure nothing gets passed :)
