### ISSUE TITLE
Battle for Markarth Observations

### ISSUE THREAD

**Issue by Eve-Knight** [schofida/CWORR#121]
Music started normally at start of siege but then stopped while the siege was still ongoing.

I'm also using JK's Markarth, so the placement of some of the barricades in the city streets was a bit odd, but I was able to get around them.

Incidentally, tabbing away from and then back into the game restored the music.

I was able to attack Ondolemar (enemy Thalmar in Markarth keep) "early" in the keep while the jarl was still talking, which gave me a bounty.

After the jarl surrenders, the music still continues in the keep and back out in the city. And Galmar forces a conversation again for no reason.

Fast traveling to Windhelm successfully gave the message that the Stormcloaks control the reach and stopped the music. Bounty still present at this point, with the Windhelm guard saying "Wait, I know you." An Eastmarch bounty makes no sense at all for this.

Talked to Ulfric. Bounty still there. Got additional objective to liberate Hjaalmarch, so still two active at once.

The "Pay faction crimes" option did not remove the bounty either.

I'll redo the keep battle and let Ondolemar shoot first ... okay, no bounty this time.

**Comment by LABWAZHERE** [comment]
Okay

**Comment by LABWAZHERE** [comment]
Wait

**Comment by LABWAZHERE** [comment]
So the issue here is I think you killed the elf, Galmar is supposed to do that

**Comment by LABWAZHERE** [comment]
I don’t blame you, I am an imperial and I KOS any thalmor I see, those bastards deserve it

**Comment by Eve-Knight** [comment]
No, it's just that it's considered assault since he had not yet attacked me.

Also, this second time around when I talked to Ulfric, he selected Falkreath instead, so no more duplicate objective.

**Comment by Eve-Knight** [comment]
It was probably an Eastmarch bounty because the "crime" was witnessed by the Stormcloaks.

**Comment by LABWAZHERE** [comment]
> It was probably an Eastmarch bounty because the "crime" was witnessed by the Stormcloaks.

Which is ironically funny considering that well Galmar kill him, in future I’d recommend letting Galmar kill him

**Comment by Eve-Knight** [comment]
Well ... that does avoid the bounty ... but it usually also avoids Ondolemar being killed at all. The combat ends whenever the jarl takes enough damage, and they tend to focus on him. So it actually takes a bit of effort to kill Ondolemar at precisely the right time to avoid a bounty.

**Comment by LABWAZHERE** [comment]
Wait what? That isn’t meant to happen

**Comment by LABWAZHERE** [comment]
Okay the real issue we have experienced here and the one I dreaded was the case is the cut execution of Ondolemar hasn’t been readded

**Comment by LABWAZHERE** [comment]
Ya see when the Stormcloaks take markarth they are meant to execute him after the Jarl surrender

**Comment by LABWAZHERE** [comment]
Okay new issue time

**Comment by LABWAZHERE** [comment]
I’ll let you do the honours

**Comment by LABWAZHERE** [comment]
Galmar says “come here elf”

**Comment by Eve-Knight** [comment]
It's been consistent for all the versions of this mod I've seen. And even in vanilla when you attack Whiterun, the battle ends when Balgruuf takes enough damage, so any remaining generic guards stop combat and live if Balgruuf takes enough damage first.

I was not aware there was ever a scene with Ondolemar being executed. That definitely wasn't in earlier versions of this mod. If it's there now, I may have skipped it by killing him myself.

Feel free to make a separate issue for it if you like. I'm okay with this issue to just catch all issues with the Markarth siege.

Come to think of it, I did notice him having a line about burning the corpse that seemed new. I guess an ideal solution would be  to make Ondolemar temporarily essential so the player gets to see Galmar execute him (if it just didn't play because I killed him myself).

**Comment by LABWAZHERE** [comment]
Okay basically in OCW, which is how I know this exists is that when the Stormcloaks take Markarth after the Jarl surrenders Galmar executes Ondolemar on the spot

**Comment by LABWAZHERE** [comment]
> 

If you don’t mind could you re do the siege again and tell me if it happens or not? I never got round to a stormcloak markarth siege that hadn’t changed hands

**Comment by Eve-Knight** [comment]
Done. Happened. It's actually "Not so fast, elf." So it works fine. It would just be better if the player was prevented from killing him so the scene was guaranteed.

**Comment by LABWAZHERE** [comment]
Noted

**Comment by LABWAZHERE** [comment]
> Done. Happened. It's actually "Not so fast, elf." So it works fine. It would just be better if the player was prevented from killing him so the scene was guaranteed.

Did Galmar still force a convo with you?

**Comment by LABWAZHERE** [comment]
If so I might boot up Skyrim on my Xbox and see if it occurs in OCW there could be missing dialogue

**Comment by Eve-Knight** [comment]
I don't think so. The execution here might short circuit that script. Or maybe I just didn't stand around waiting for it long enough.

**Comment by schofida** [comment]
> Music started normally at start of siege but then stopped while the siege was still ongoing.

So I regrettably can't test this at all. I am testing CWO on a Bootcamp'd Macbook and I cannot get music to work period from some reason. But CWO does not change how the music starts/stops.

> I'm also using JK's Markarth, so the placement of some of the barricades in the city streets was a bit odd, but I was able to get around them.

I think some patches for town/city mods will be needed. Hopefully I will get some help to toggling these after release.

> I was able to attack Ondolemar (enemy Thalmar in Markarth keep) "early" in the keep while the jarl was still talking, which gave me a bounty.

This will hopefully be fixed in #122 

> After the jarl surrenders, the music still continues in the keep and back out in the city. And Galmar forces a conversation again for no reason.

I think there is another issue for the force conversation. Rikke and Galmar both do this. Its vanilla behavior.

> Fast traveling to Windhelm successfully gave the message that the Stormcloaks control the reach and stopped the music. Bounty still present at this point, with the Windhelm guard saying "Wait, I know you." An Eastmarch bounty makes no sense at all for this.

Yeah this does not make sense. Are you sure the 'Wait I know you' didn't come from something else?

> The "Pay faction crimes" option did not remove the bounty either.

This only pays off the invisible CWImperialCrimeFaction and CWSonsCrimeFaction that happens when you kill your own side via friendly fire.

**Comment by Eve-Knight** [comment]
Yeah, it was definitely an Eastmarch bounty. I checked the crime stats screen.
