### ISSUE TITLE
Ondolemar’s execution by Galmar 

### ISSUE THREAD

**Issue by LABWAZHERE** [schofida/CWORR#122]
Okay basically in OCW, which is how I know this exists is that when the Stormcloaks take Markarth after the Jarl surrenders Galmar executes Ondolemar on the spot

does this happen in this mod? This question stems from a convo between me and eve in issue #121

**Comment by LABWAZHERE** [comment]
Update: works fine maybe just make him essential until Galmar kills him so the player can’t kill him

**Comment by schofida** [comment]
done. Should be fixed in next release.
