### ISSUE TITLE
Spy Problem

### ISSUE THREAD

**Issue by Eve-Knight** [schofida/CWORR#125]
I entered Solitude. It's controlled by the Imperials. I'm a Stormcloak. I have the disguise mechanic disabled. I understand this to mean that it acts like vanilla and that I will not be attacked by guards outside of the actual civil war battles.

I notice combat nearby and see there's a Stormcloak Spy. All as expected so far ...

The issue is that the guards then started to attack me, even though I did nothing to involve myself. Worse, killing (some?) of the guards gave me a murder bounty.

There's unfortunately not much I can do to reliably trace the precise chain of events because the save I have is from entering the city and before the random spy event was triggered.

Come to think of it, though, I am using Path of Sorcery and have an effect (Aura of Light) that constantly heals nearby "friendly people." So maybe it healed the Stormcloak Spy which then generated aggro from the guards. Are they all "friendly" just because they aren't attacking me? Or is it just the spy that's friendly because I'm a Stormcloak? If it's the latter, then changing them to be neutral instead should fix this.

**Comment by ds-nscorp** [comment]
So the Spy Mechanic basically takes whatever side a random guard is on and basically just swap factions. I've always had a problem this but you just gave me great idea. I think instead of swapping factions, I might make a spy faction that will be hostile to the player (if the player is in the opposing faction) and whatever it's target is. I think that will help with a lot of the complications.

**Comment by LABWAZHERE** [comment]
Yeah that’s an annoying bug I do think it shouldn’t be a murder bounty

**Comment by schofida** [comment]
Looking at this next

**Comment by schofida** [comment]
I might have fixed this. So all NPC's relating to the Civil War have 2 factions (like Stormcloaks have a CWSonsFaction and CWSonsFactionNPC).

CWSonsFaction sets themselves as allies to other CWSonsFaction NPCs.
CWSonsFactionNPC sets themselves as enemies to CWImperialFactionNPC NPCs.

So when an NPC gets chosen to become a spy, I remove all the factions that the NPC belongs to and add both opposing factions. What I changed was to only add the 'NPC' faction. That way, you and the spy are not necessarily allies so these cloak healing effects will hopefully not work on the spy thus making everyone else mad at you.
