### ISSUE TITLE
Alternative Start Issues (Nexus user reported)

### ISSUE THREAD

**Issue by LABWAZHERE** [schofida/CWORR#126]
user said:
"interesting bug, if you add mid playthrough, i haven't started civil war nor the peace meeting, i have an alternative start mod, but hadvar is alive and my race is imperial. i get attacked on site at every stormcloak province, is that because of my race, a bug, because i saved hadvar. i have no clue and even when i change the MCM to conceal my identity it still docent work, it also always is saying im in whiterun despite me loading into riften, only just installed and not sure how to fix 

i will continue without for now and wait for either solution or new playthrough cause i really wanna give it a go"

I asked them these questions:
"1. What version is this? (Nexus or GitHub)

2. Is your disguise setting set to realistic or default?
(CWOR adds a feature where if you’re in an enemy controlled hold you get attacked on site, the mcm menu has a feature that allows you to toggle this to realistic where you’ll only get attack while wearing the Curiass of your faction 

3. the above feature is buggy in nexus build the GitHub build the feature works fine 

4. what alternate start mod is it?"

User responded with:
"1. github
2. i tried all types of disguise settings however still disguised i got attacked 
3. i got the most recent github however i did install mid playthrough
4. Alternative start - live another life (however i had gone back to helgen and ended up giving hadvar a potion)

not sure why it happened but it was only on this imperial character and not any other and it was only stormcloak areas."

I told them that I can't remember if we had alternative start issues so i told them i'd bring it up with you Schofida.

**Comment by ds-nscorp** [comment]
Thanks for the report. I will look into this when I can. In addition to work I'm now feeling a little under the weather :(

**Comment by LABWAZHERE** [comment]
Oof get well soon

**Comment by schofida** [comment]
Thanks! I did get better :)

i 100% always use alternate start and did not have any issues. Do you happen to know the Nexus user? I can send him/her a DM. So there is a disguise quest that CWO manages and may have stopped for a siege but failed to turn back on (which never happened to me but Skyrim does also have a terrible engine 😕) Maybe I can add a safeguard to the MCM to jump start it if the user changes the disguise mechanic.

**Comment by LABWAZHERE** [comment]
humbleLLDE

**Comment by schofida** [comment]
I never got a chance to message the user but toggling the disguise mechanic in the MCM will always turn the disguise quest on in case something failed to start. https://github.com/schofida/CWORR/releases/v1.0.16a
