### ISSUE TITLE
Nexus question - does the Wintersrun Patch still work?

### ISSUE THREAD

**Issue by LABWAZHERE** [schofida/CWORR#127]
user said:

"Does the newer Github version still require the Wintersun patch if both mods are present?

Looking in xEdit makes it seem like it isn't necessary, but I'd prefer to get confirmation, if it happens to be known"

**Comment by LABWAZHERE** [comment]
To add to this,  I myself will ask

do all the patches work / are they required for compatibility with the GitHub versions?

**Comment by LABWAZHERE** [comment]
also on an unrelated note I made this image for CWORR
![Civil War Overhaul Redux Redux](https://github.com/schofida/CWORR/assets/128126252/c1194fec-2a0d-47c5-b9f3-40db777c613f)

**Comment by schofida** [comment]
None of these patches are needed anymore (except the Boethiah's Bidding patch which will require an update). I dug out all of Boethiah's quest from CWO. I also went to great effort to get all of the functionality out of the CW quest. Some of the armor replacers for some reason overrode the CW quest line which would utterly break previous iterations of CWO
