### ISSUE TITLE
Move tulius’s pre final siege speech?

### ISSUE THREAD

**Issue by LABWAZHERE** [schofida/CWORR#128]
In tulius’s final speech he mentions “across this bridge”  then mentions the windhelm defences separately. he usually spawns in front of the windhelm war camp, I interpreted these lines in his speech as being one of 2 places.

1. That bridge to windhelm on the left\
![20230529141055_1](https://github.com/schofida/CWORR/assets/128126252/0b57df30-c3f9-49fc-a8b8-a201fba5c648)

2. The walkway just outside Windhelm before the brick part right next to the stables (the catapults don’t reach there)
![20230529141037_1](https://github.com/schofida/CWORR/assets/128126252/2a6e24f3-460c-4cd4-aa3b-250df0defa3c)

**Comment by schofida** [comment]
> In tulius’s final speech he mentions “across this bridge” then mentions the windhelm defences separately. he usually spawns in front of the windhelm war camp, I interpreted these lines in his speech as being one of 2 places.

It's 2. (In regards to the catapults, that's still an open item. If you haven't noticed, the Imperial Camp catapults don't fire :(  )

**Comment by LABWAZHERE** [comment]
> If you haven't noticed, the Imperial Camp catapults don't fire :( )


Never noticed, but I was referring to the ones coming from windhelm their projectiles miss those locations
