### ISSUE TITLE
Rescue from other forts

### ISSUE THREAD

**Issue by LABWAZHERE** [schofida/CWORR#129]
The cut mission content suggests rescue from other forts was possible additionally to my understanding most coding for the other forts is in place

**Comment by LABWAZHERE** [comment]
Update: nvm I read it wrong I don’t think there is enough coding for this.

 but leaving it open so I can get your professional confirmation

**Comment by schofida** [comment]
I am hardly a professional lol. But you are right. This is specifically coded for these 2 forts. The other forts are missing all of the markers, prisoner aliases and everything else needed to make this quest work :( It's a shame because the dialogue lines support this.

**Comment by LABWAZHERE** [comment]
> I am hardly a professional.

don’t be so hard on yourself the amount of time you’ve been working on this mod you’re basically one of the few people excluding simtam (that guy is on another level of cw knowledge ) who have extensive knowledge of the civil war and how it functions
