### ISSUE TITLE
Idea: add a patch for or add the mod repair cities

### ISSUE THREAD

**Issue by LABWAZHERE** [schofida/CWORR#13]
The mod repair cities will activate after a Last stand Battle of Solitude or Windhelm (even on victory) it'd be cool if you could add a patch for it so it doesn't trigger until the actual end of the war

**Comment by schofida** [comment]
Added to CWO Feature board https://trello.com/c/oriCBJmC/37-add-a-patch-for-or-add-the-mod-repair-cities
