### ISSUE TITLE
Cwmissions 10&11?

### ISSUE THREAD

**Issue by LABWAZHERE** [schofida/CWORR#130]
![6F8C8C48-E168-459C-9EB0-682FFACE10DB](https://github.com/schofida/CWORR/assets/128126252/206e8a50-3083-4e67-bb5e-358fbd91386f)

Are either of these possible?

especially with allies I know of quite a few NPCs that could be added to cwallies faction

Additionally 
11 the one with the orc could be an imperial exclusive, even though Rikke and Galmar both have dialogue for the giant and orc quests, we could make the Goldar and orc quests faction exclusive (stormcloak Goldar imperial orc)

if not possible that’s fine these ones don’t need to be added,

however mission 00 might be interesting since spys/scouts are already implemented but it could still be too much work considering there are only 2 scripts

**Comment by LABWAZHERE** [comment]
Additionally ima just stop suggesting things that aren’t bug fixes and may require a bunch of effort

as the backlog is getting very big and I don’t want to put too much pressure on you.

**Comment by schofida** [comment]
Unfortunately both of these have almost nothing remaining from the base game. CWMission11 really does not have anything to do with the Civil War and the base game is missing everything from dialogue to whatever this 'Gar-shutan' thing is. CwMission10 does not have any dialogue and based on the quest description, I don't really know how to build a quest around that beyond a basic fetch quest (in this case, talking to somebody).

**Comment by LABWAZHERE** [comment]
Fair enough, didn’t think they were able to be restored wow Bethesda really good game you made here guys, thanks todd
