### ISSUE TITLE
X marks the docs alternatives

### ISSUE THREAD

**Issue by LABWAZHERE** [schofida/CWORR#131]
According to the cutting room floor site

 “The documents could spawn at one of two random locations for every war camp and most Jarl's residences, with the exceptions being Castle Dour, which has three possible locations, and Dragonsreach, which has four possible locations where they could spawn.”

Is it possible to randomise the location of the war documents to be either in the war camp or in the Jarls residence?

**Comment by schofida** [comment]
I think I can do this :)

**Comment by schofida** [comment]
This has been added to https://github.com/schofida/CWORR/releases/tag/v1.0.15a
