### ISSUE TITLE
Defence of Whiterun (Spanish inquisition) giant raid

### ISSUE THREAD

**Issue by LABWAZHERE** [schofida/CWORR#132]
Okay so after triggering a defence mission of Whiterun (Spanish inquisition) the battle works fine except for one thing, many giants. I am fine with one Giant helping but I encountered like 3 (not simultaneously but consecutively) if I wasn’t on god mode I’d probably have lost (additionally character was on level 2 but had all perks unlocked)

Maybe giant Easter egg should be leveled or only appear on higher difficulties or levels

**Comment by LABWAZHERE** [comment]
additionally i don't know if this caused it or not but
![20230529151133_1](https://github.com/schofida/CWORR/assets/128126252/adeb7fe7-21c4-4628-9e0c-a2744ac02dfd)

the drawbridge is stuck like this, i can not move it

**Comment by schofida** [comment]
> Okay so after triggering a defence mission of Whiterun (Spanish inquisition) the battle works fine except for one thing, many giants. I am fine with one Giant helping but I encountered like 3 (not simultaneously but consecutively) if I wasn’t on god mode I’d probably have lost (additionally character was on level 2 but had all perks unlocked)

> Maybe giant Easter egg should be leveled or only appear on higher difficulties or levels

I am handling this under #51 But if you have CWOLeveled esp enabled, Giants should not be showing up until level 36.

> additionally i don't know if this caused it or not but the drawbridge is stuck like this, i can not move it

This is a vanilla bug. I added a routine to the 'Get CWO Quest Unstuck' to fix the bridge. Can you try it?

**Comment by LABWAZHERE** [comment]
I will try when I get home I am out atm

**Comment by schofida** [comment]
I had to adjust the condition but now selecting the 'get civil war unstuck' should fix the bridge
