### ISSUE TITLE
Idea: renaming some missions?

### ISSUE THREAD

**Issue by LABWAZHERE** [schofida/CWORR#133]
I don’t know if it will mess somethings up but if some missions could be renamed here are some ideas I came up with

on defence, battle of is replaced with Defence of (excluding the battle of Whiterun on imperials side)

last stand battles on defence will be called
The Stormcloaks final stand or the final stand of Solitude.

X marks the docs and ___ final battle are good names

Defector Collector is a good name as well. the only way I could think of improving it is Dissent Disenchanted or Dissident Dissolution.

**Comment by schofida** [comment]
Regrettably no. (Or at least I don't know how) I know that you can't programmatically cannot change quest names. Defensive/offensive quests for major cities are all handled by the cwsiege quest (with minor siege quests being handled by cwfortsiegecapital quest). Quest names can be dynamic but they need an Alias label (such as the city). I don't know how to create a label alias or something like that.
