### ISSUE TITLE
Map markers not disappearing?

### ISSUE THREAD

**Issue by LABWAZHERE** [schofida/CWORR#134]
I only have one mission to go off of so far but from my playing of the first battle of Whiterun (imperials) I noticed that none of Whiteruns map markers (dragonsreach, Whiterun and Whiterun stables) vanished, is this normal? 

Edit also occurred with Spanish Inquisition quest in Whiterun too

**Comment by LABWAZHERE** [comment]
update:  works fine for other sieges

**Comment by schofida** [comment]
So the first siege quest for Whiterun is different. It does not fire until you enter Dragon's Reach (Stage 0) and then the quest actually starts when you talk to Cipius (stage 1). The Stromcloaks, Battle for Whiterun fires during the 'Message to Whiterun' quest. Once the quest started after you talked to Cipius, were the Markers still there?

**Comment by LABWAZHERE** [comment]
Yes that’s correct which I found weird
