### ISSUE TITLE
fort commanders - incompatabilities

### ISSUE THREAD

**Issue by LABWAZHERE** [schofida/CWORR#136]
with fort commanders when the Kill the commander objective pops up (when low on enemy troops), when you enter the fort he isn't in there and it says 

completed: attacking forces 0
making the fort battle impossible to complete

**Comment by LABWAZHERE** [comment]
additionally battle for fort neugard (imperial defence) still will keep going after all my team is dead and i have fast travelled away
![20230529154207_1](https://github.com/schofida/CWORR/assets/128126252/9c0dc4be-4f14-4399-8d14-fdcb47f4788f)
![20230529154430_1](https://github.com/schofida/CWORR/assets/128126252/3ff296a2-6ffa-4817-a9fb-644f2fb71420)

**Comment by schofida** [comment]
> with fort commanders when the Kill the commander objective pops up (when low on enemy troops), when you enter the fort he isn't in there and it says

> completed: attacking forces 0
making the fort battle impossible to complete

I will take a look at this.

> additionally battle for fort neugard (imperial defence) still will keep going after all my team is dead and i have fast travelled away

But this I need to take a look at. Where did you teleport to? Battle for Fort Neugrad should not be happening at all (maybe it is firing on Defense)

The reason being... Battle for Fort X sieges may finish. But the fort sieges do not actually complete until you are out of the Fort Location which unfortunately for the Stormcloaks is so close to the camp that the Fort Neugrad location overlaps with the Falkreath Stormcloak Camp. So I hardcoded the Battle of fort Neugrad to happen at all. (Note this works differently from the 'Rescue from Fort Neugrad' (CWMission04) quest)

**Comment by LABWAZHERE** [comment]
Yeah sorry defence mission, and I went to Whiterun and like an area in falkreath that was further away from the stormcloak camp when I took that journal pic I was in riverwood

**Comment by LABWAZHERE** [comment]
Will also point out with the offence fort mission (not neugrad) there was a marker to kill the commander but he didn’t spawn in which I think is because the enemy ran out of troops before I could kill him. Which is why it wasn’t completable cause the commander didn’t spawn

**Comment by schofida** [comment]
This should be resolved now. You will probably need both https://github.com/schofida/CWORR/releases/tag/v1.0.15a and https://github.com/schofida/CWORR/releases/tag/SCWOFC
