### ISSUE TITLE
false front- map flags get shy

### ISSUE THREAD

**Issue by LABWAZHERE** [schofida/CWORR#137]
in imperial pale camp
![20230529142013_1](https://github.com/schofida/CWORR/assets/128126252/964099ed-efb0-4521-91f8-d167627553bc)

**Comment by schofida** [comment]
Hmmm... I will take a look but CWO does not do anything to these...

**Comment by LABWAZHERE** [comment]
Could be a vanilla thing but I haven’t done vanilla civil war for years at this point

**Comment by DarthVitrial** [comment]
The bug happens in vanilla too due to a papyrus error, see here: https://afktrack.afkmods.com/index.php?a=issues&i=%2022948

**Comment by ds-nscorp** [comment]
Thank you! I saw arthmoor's comment. That should be an easy fix.

**Comment by schofida** [comment]
Fixed in 1.0.17
