### ISSUE TITLE
morthal defence never started - Spanish Inquisition

### ISSUE THREAD

**Issue by LABWAZHERE** [schofida/CWORR#139]
mods words not mine. it didn't start, the co vanished and the Field Co map markers (physical) got shy

infact morthals general was nowhere to be seen even before it started

**Comment by LABWAZHERE** [comment]
update: waited an hour he appeared

**Comment by LABWAZHERE** [comment]
also would like to know what spanish inquisition means about 100 setting cause it isn't 100%

**Comment by LABWAZHERE** [comment]
update update: uh i think spanish inquisition broke..... it isn't giving me defence quests in holds anymore

**Comment by LABWAZHERE** [comment]
idk if this is related but the whiterun bridge is raised
![20230529151133_1](https://github.com/schofida/CWORR/assets/128126252/967dfa12-5f91-48d7-be53-008afdd739a8)

**Comment by LABWAZHERE** [comment]
mcm
![20230529151259_1](https://github.com/schofida/CWORR/assets/128126252/a3ec5d80-e78f-4ee2-b7f0-fe5141d3d292)

**Comment by LABWAZHERE** [comment]
UPDATE UHHHHHHHHHHHHH
![20230529151454_1](https://github.com/schofida/CWORR/assets/128126252/923419e9-55ce-4736-b51a-448007125506)
![20230529151457_1](https://github.com/schofida/CWORR/assets/128126252/0262d33d-1927-490c-a651-f3ff55e61ea5)
(havent done any quests for winterhold)

additionally i spoke to the morthal general when he appeared and nothing happened

**Comment by LABWAZHERE** [comment]
morthal map marker disappeared

**Comment by LABWAZHERE** [comment]
siege worked fine and is functioning normally now

**Comment by schofida** [comment]
Just wanted to confirm:

1. A Spanish Inquisition started for Morthal
2. The Field CO for Morthal did not show up but waiting an hour later and he did?
3. But when he did show up he didn't have anything to say?
4. So you went to Rikke and she erroneously gave the 'We're taking Winterhold' speech since that was what the offensive campaign was?
5. So you went back to Morthal and successfully defended it?

**Comment by LABWAZHERE** [comment]
Correct  successful defence well not successfully I intentionally lost but it still triggered a fail condition. I will point out that the mod said the morthal defence failed to start please contact mod author

**Comment by schofida** [comment]
> I will point out that the mod said the morthal defence failed to start please contact mod author

Ah crap. This is why. I'll take a look!

**Comment by LABWAZHERE** [comment]
I will just say apart from this and the fort commanders issue the mod was running smoothly apart from the occasional … from tulius and Rikke  and Balgruufs speech issue

the mod went swimmingly, I think it is almost ready

**Comment by schofida** [comment]
This should be fixed now in https://github.com/schofida/CWORR/releases/tag/v1.0.15a
