### ISSUE TITLE
Feature - Patch for Conquest of Skyrim Mod

### ISSUE THREAD

**Issue by LABWAZHERE** [schofida/CWORR#14]
Leaving this open as a reminder for Conquest of Skyrim patch. All other issues have been moved to their own pages.

**Comment by LABWAZHERE** [comment]
From my research the Stormcloaks appears to be more stable (and actually playable) than the imperial side, seems Apollodown had a preference. Anyway i don't know if the same bugs will appear in the stormcloak quest (Tulius not dying) but i am testing it now

**Comment by LABWAZHERE** [comment]
the ulfric not dying issue was on my end but the rest still stands

**Comment by schofida** [comment]
@LABWAZHERE I am glad you discovered the immortal Ulfric issue. Can you let me know what you found? If it is a mod conflict, I will put on the mod page once this version is ultimately resleased.

**Comment by LABWAZHERE** [comment]
the conquest of Skyrim mod for some reason makes Ulfric immortal their mod is a work in progress still but a patch for it maybe good

**Comment by LABWAZHERE** [comment]
there are a few more things to add to compatibility issues with conquest they are listed below as such

1.Riften imperial camp burns down while on imperial side 
![20230318211326_1](https://user-images.githubusercontent.com/128126252/232358030-1fbae425-d8fa-4342-bf62-e4d2ce86e61b.jpg)
(can't have shit in Riften) and will reappear during riften siege while on fire 
2. The siege markers from conquest will appear for some fort sieges and won't Despawn.
![20230319092205_1](https://user-images.githubusercontent.com/128126252/232358482-74a535e3-5a0a-402e-a42c-c76722ec4607.jpg)


3. You can burn down camps during the war.
(these were found ages ago but i forgot to add them to this list)

Note: these happened during the civil war, conquest doesn’t auto activate you need to manually activate it by reading a book, theoretically these things ( burning camps and siege markers) shouldn’t occur until you activate conquest

**Comment by LABWAZHERE** [comment]
important note: conquest will activate reunification after the defeat of Alduin if you use the mcm to win the war i don't think it will activate liberation since conquest kinda relys on you having both ulfric and tulius alive

**Comment by schofida** [comment]
Added to CWO Feature Board https://trello.com/c/khPJYSWX/38-patch-for-conquest-of-skyrim-mod
