### ISSUE TITLE
... (dialogue issues)

### ISSUE THREAD

**Issue by LABWAZHERE** [schofida/CWORR#142]
okay so basically was given 2 missions by rikke (x marks the docs and sabotage at lorieus farm) Rikke said "we need the documents" after which it activated x marks the docs (which is normal) but it was then just followed by ..., this also happens when you reach legate and speak to tulius after giving the location to go to next he just says ...

**Comment by schofida** [comment]
> okay so basically was given 2 missions by rikke (x marks the docs and sabotage at lorieus farm) Rikke said "we need the documents" after which it activated x marks the docs (which is normal) but it was then just followed by ...

This ... is a catchall that the dialogue tree hits when the variables aren't properly set (which I do set). This has happened to me once as well. I tried to track it down but was unable to duplicate it. I think this just needs to be chalked up to Skyrim wackiness

> this also happens when you reach legate and speak to tulius after giving the location to go to next he just says ...

Same thing. Although this time, you are already at Legate and can't rank up anymore so it hits the .... I know its jarring but unfortunately Skyrim needs to display something or it breaks the dialogue tree.

**Comment by LABWAZHERE** [comment]
> Same thing. Although this time, you are already at Legate and can't rank up anymore so it hits the .... I know its jarring but unfortunately Skyrim needs to display something or it breaks the dialogue tree.

OCW just has Tulius say "Legate" or "queaster" to break the dialogue scenes, maybe do something like that?

**Comment by ds-nscorp** [comment]
Ugh! This is a good idea!! ☹️
