### ISSUE TITLE
scwofc - Fort commanders don't wear commander clothes

### ISSUE THREAD

**Issue by LABWAZHERE** [schofida/CWORR#144]
![20230620142145_1](https://github.com/schofida/CWORR/assets/128126252/1adeb038-1876-4dc8-97e0-ed326e792aff)

additionally i am on level 100, I think It'd be cool if fort commanders scaled with your level (i mean this is the fort commander we're talking about here at least put up a fair fight)

**Comment by schofida** [comment]
Can you let me know the load order? I have CWO, SFCWFC, then SFCWOFC

**Comment by LABWAZHERE** [comment]
i don't have the original i hae CWO SFCWOFC

**Comment by schofida** [comment]
This is fixed. Required SCWFC base in the patch
