### ISSUE TITLE
X's Final Battle Bugs

### ISSUE THREAD

**Issue by LABWAZHERE** [schofida/CWORR#15]
1. The Dawnstar general doesn't appear (imperial side), it won't progress automatically, had to do it via mcm
![20230318184505_1](https://user-images.githubusercontent.com/128126252/226101533-03ca5bbc-2c69-41f7-9075-43c13a160fdf.jpg)
![20230318184825_1](https://user-images.githubusercontent.com/128126252/226101536-27aecafe-0154-4675-b1e6-8acb8bfbb604.jpg)

2.  Winterhold quests doubled up the general, he ded, but rikke wants him ded. (already completed the quest and rikke asked me to do it again had to resurrect him and kill him again)
![20230318193056_1](https://user-images.githubusercontent.com/128126252/226101582-fa634a3b-8b29-4892-879b-d3c8c0214c7d.jpg)

**Comment by schofida** [comment]
Thanks for reporting this. You are not the only person to report the Pale General not showing up. I could not reproduce and I have no idea why this is happening. Do you happen to remember if the quest marker was pointing to the field co in Dawnstar or the field co in the Stormcloak camp? (every field co has a twin, making setting this quest up extra fun)

In regards to why Rikke gave that quest twice in Winterhold, I have no idea but I will check. I check a ref alias fill condition on the quest to make sure that the commanding officer is alive.... UGH this game engine!

**Comment by LABWAZHERE** [comment]
Dawnstar hold, actually no. i had no waypoint. he definitely is there cause i visited Dawnstar to beat up the Stormcloak jarl for no reason and he was there so yeah that is confusing, thanks for the best game ever bugthesda

**Comment by ds-nscorp** [comment]
I made some adjustments here as well. These issues might be fixed in v1.0.3a

**Comment by LABWAZHERE** [comment]
dawnstar untested however new issue has emerged
whiterun stormcloak general won't die in camp (he doesnt take damage he just attacks.) to add to this he doesn't appear in dragonsreach and simir is dead (i don't remember killing simir in this play through but knowing me and my justified intense hatred of the stormcloaks i probably did to send a message to vignar)

also important to note HE CAN NOT BE KILLED NOT EVEN BY USING A MOD THAT CAN ALLOW ME TO DISABLE ACTORS. NO MAN SHOULD HAVE THIS POWER ESPECIALLY IF THEY ARE A STORMCLOAK

**Comment by schofida** [comment]
Is this on a playthrough where you did Season Unending to defect to the Imperials from the Stormcloaks? Who was the target supposed to be?

Yeah all of the generals are marked as essential by default. The cwmission05 quest programmatically is supposed to         
de-god them

**Comment by LABWAZHERE** [comment]
Hjornskar Head-Smasher and yes it was that playthrough

**Comment by LABWAZHERE** [comment]
> Is this on a playthrough where you did Season Unending to defect to the Imperials from the Stormcloaks? Who was the target supposed to be?
> 
> Yeah all of the generals are marked as essential by default. The cwmission05 quest programmatically is supposed to de-god them

so basically it is similar to the dawnstar issue where he either isn't appearing in dragonsreach which is where i am meant to kill him or his pathfinding is broken. additionally the invulnerable Hjornskar is the one at the Whiterun camp 

another important note, during the defectors quest the co's should be essential so they don't die prematurely.

**Comment by LABWAZHERE** [comment]
okay another bug
![20230417102803_1](https://user-images.githubusercontent.com/128126252/232353277-f5b92157-ef8a-4858-bf05-6877c1aa462e.jpg)
killing kai wet pommel makes his body hit the floor before the animation is complete. 

in addition to this when you try to leave the jarls long house it crashes, everytime. 

i don't have any winterhold mods and stealing the docs quest had no crash (i got this quest from rikke after killing him)
i got it to not crash by using the cheat room mod (god bless bradenm1's soul, i would not have been able to struggle through the xbox 1 version unstability)  to teleport to the cheat room and using it to teleport to a different hold (i don't use console as much since as a former xbox player bradenm1's cheat room does an almost perfect job instead)



only killing kai causes this to occur. when the quest isnt active i can just stroll in and out no issue

another piece of info i had an auto save after i exited jarls longhouse and it still crashed when it tried to autosave. it didn't do this before.

this is probably just an issue on my end but it is still worth looking into just in case

**Comment by ds-nscorp** [comment]
It's not you. That was happening to me too outside of Falkreath's HQ. I realized that I inadvertently messed up an ID on the quest alias which caused a duplicate alias ID. I corrected and ran the quest again without problems. This was on v1.0.6a.

Regardless. I don't think that this quest is accounting for switching sides so I think that this quest may need a re-design ☹️ anyway

**Comment by LABWAZHERE** [comment]
yeah also happens with kottir red shoal
on an unrelated note what is with the ridiculous names of the stormcloak generals? like seriously guys have normal names

**Comment by schofida** [comment]
> like seriously guys have normal names

LOL Agreed.
I believe that I simplified a lot of the things with this quest which should make it more stable. I hope to have a new release out tomorrow.

**Comment by schofida** [comment]
Closing this issue as I tested pretty extensively yesterday and everything appears to be working ok.

As info: these FieldCO's are obnoxious as each one has a twin (one in the Capital HQ and if the camp is enabled there is one in the camp). I was doing all sorts of stuff to make sure that each one is accounted for and that the Skyrim engine did not arbitrarily pick the wrong one. However, I ended up scaling the complexity back quite a bit and instead just flagged both (if the camp is not enabled, it just gets the HQ one). So when you turn quest markers on, something strange happens. If the camp is enabled, you will see 2 markers. Which looks weird but I think that this offers the most flexibility. You can then go after either or. Killing one, kills both of them and the Skyrim default clean up script will eventually clean up the bodies.
