### ISSUE TITLE
Refs needing persistence

### ISSUE THREAD

**Issue by DarthVitrial** [schofida/CWORR#150]
This is really minor/irrelevant since this mod isn't esm-flagged, but I scanned the most recent build with the Persistify script (https://www.nexusmods.com/skyrimspecialedition/mods/76750) and it detected two records that should be Persistent but aren't:

WFieldCOImperialHaafingar "Legate Adventus Caesennius" [NPC_:000844B1] - ([ACHR:0842B69A])
CWFieldCOSonsEastmarch "Yrsarald Thrice-Pierced" [NPC_:00084551] - ([ACHR:0842B69B])

(the ACHR ones are the ones that need the Persistent flag)

**Comment by schofida** [comment]
Thank you! Fixed in 1.0.17
