### ISSUE TITLE
Cannot Move Character After Adjusting MCM Setting

### ISSUE THREAD

**Issue by Eve-Knight** [schofida/CWORR#151]
Started new game. In Helgen, adjusted MCM setting to disable disguise mechanic. After exiting the menu, my character's animation showed continuous forward walking but I stayed in place. Could not exit this state short of loading an earlier save. Maybe an Improved Camera SE incompatibility.

**Comment by Eve-Knight** [comment]
Looks like this specifically occurs only when bound now, so not a major concern. Worked fine after bonds were cut inside Helgen Keep.

**Comment by schofida** [comment]
Thanks for the report. I am reverting the MCM feature so that it does not run through the Disguise mechanic unless the quest is running.
