### ISSUE TITLE
Papyrus Error in 1.0.22?

### ISSUE THREAD

**Issue by DarthVitrial** [schofida/CWORR#153]
After updating to the latest version I'm getting the following Papyrus error:
WARNING: Property MQ302 on script CWOArmorScript attached to alias Player on quest CWOArmorDisguise (2A013B4F) cannot be initialized because the script no longer contains that property

**Comment by ds-nscorp** [comment]
Thanks! It should be benign but I will address. I have been sick the passed couple weeks but I am starting to feel better so I will be working on another update soon.
