### ISSUE TITLE
Seasons unending neutrality. - killing adluin launches you into a side

### ISSUE THREAD

**Issue by LABWAZHERE** [schofida/CWORR#154]
Hello again it has been a while, i won't be doing too many bug reports but had to mention this one as it is notable egregious.

to start conquest of Skyrim was installed, so it could possibly be conquest causing most of the issues but

when doing the peace treaty while unaligned with either side when you kill Alduin, it defaults to making you join the imperials (might work with Stormcloaks, but considering i was very reasonable to them in the treaty idk)  

the reason i bring this up is because conquest of skyrim makes Ulfric invincible unless killed when wiping out the Stormcloaks for your own faction making imperial Post game playthroughs impossible.

I have also found that conquest is fine to have active in your save provided you don't take the steps to activate the mods Questline.

and yes i know the obvious answer is to disable conquest until the civil war is completed but i have found activating the voice files mid save will cause it to not work.

I don't have this save still, it got corrupted.

**Comment by ds-nscorp** [comment]
Hello my friend!

Yes, that is a bug. It actually does not force you into a side but it sets the objectives off pre-maturely. I detail how to fix in one of the Bugs on the mod page. But I am hopefully going to be pushing another release soon.

**Comment by schofida** [comment]
Should be fixed now on Nexus version 1.0.24
