### ISSUE TITLE
Issues with Hold quests starting after losing them

### ISSUE THREAD

**Issue by schofida** [schofida/CWORR#20]
after you lose all holds it is possible to reclaim them up til the battle for Winterhold, (my guess for why i have markarth is because markarth is one of the tradable holds but even that idea doesn't hold up under scrunity) after that the reporting for duty does not appear and must be started manually through the mcm force start siege option, this does not apply to Whiterun (at least if you lose the first battle for Whiterun idk about winning it the first time) - a possible fix is readding the cut ability of choosing where to reclaim next as a dialogue option (another feature bethesda was too lazy to add) think of it as a dialogue debug option to force start quest. dialogue could be something like "let me suggest [hold name]".
example of bug below:
![image](https://user-images.githubusercontent.com/14967936/226152558-0c52bd77-ac7d-41a0-bef3-c88ac01ca730.png)
![image](https://user-images.githubusercontent.com/14967936/226152570-f631ad49-bba1-448e-ae3f-bcb8f4cace60.png)

the only way to progress is by manually winning Whiterun trough the Win hold here MCM option.

**Comment by schofida** [comment]
@LABWAZHERE

I will take a look. Setting the dialogue conditions on the 'Reporting for Duty' dialogue tree are very painful. What was the previous hold that you were trying to take? Can you tell me if you got some kind of victory message like 'Taking control of XXXX puts us at a .....' and then it just didn't continue after that? Or you didn't just get anything at all from Tullius?

Also, you keep mentioning Whiterun but in your screenshot, the current that you are on the Offense for is Falkreath. Is that screenshot for something else?

> a possible fix is readding the cut ability of choosing where to reclaim next as a dialogue option (another feature bethesda was too lazy to add) think of it as a dialogue debug option to force start quest.

I am not a fan of this. I don't think that a commander would get from a soldier on where they should go next. Also, the next hold is already chosen (like Falkreath in your screenshot). It is just not progressing due to Bethesda's very confusing dialogue conditions. I think what I will do instead is add something to the 'Get CWO Unstuck' routine to move the quest along. But as said, if I am able to conditions right, then the player should not need to do anything.

**Comment by LABWAZHERE** [comment]
the last hold i claimed was Winterhold, Tulius has no reporting for duty dialogue. This may also be a conflict issue with conquest of Skyrim but i am going back through without it to double check. i don't think it is though because the issue with conquest is mainly with Whiterun and it may just be because the game registers having Winterhold as being the last hold before Windhelm or it could be related to the concurrent holds glitch

**Comment by schofida** [comment]
Closing this as a possible duplicate of #42
