### ISSUE TITLE
MCM Usage to take holds prevents progression

### ISSUE THREAD

**Issue by schofida** [schofida/CWORR#21]
when you do the method mentioned in bug 4 legate rikke does not move to Eastmarch camp imperial camp and instead she just sits in castle dour waiting for you to come (she does appear in the final battle with tulius.)

using the mcm to take a hold also prevents progression

**Comment by schofida** [comment]
@LABWAZHERE Can you try this again? I made a bunch of fixes to the MCM so handling running campaigns and changing holds should work now. New version is in the Release section.

**Comment by LABWAZHERE** [comment]
yes testing them all now

**Comment by schofida** [comment]
> Can you send me a screenshot of the debug? Where are you and what are you trying to do via the MCM?

campaign phase thing, still won't work, the mcm menu for 6 quests before hold battle that's what i meant

_Originally posted by @LABWAZHERE in https://github.com/schofida/CWORR/issues/12#issuecomment-1492791461_

**Comment by ds-nscorp** [comment]
Sorry I still need a little more information. What did you tick in the MCM and what were you expecting to happen?

**Comment by LABWAZHERE** [comment]
this
![20230402080913_1](https://user-images.githubusercontent.com/128126252/229316250-c2257ba7-305b-40d6-8fd4-61a56e851eaf.jpg)
it is like very broken can't move it with mouse only keyboard and in multiples of 2
other than that hold progression works fine

**Comment by ds-nscorp** [comment]
Ah thank you. I forgot about that. It might be an MCM bug. I just pushed release v1.0.3a to display a different way. I did not get a chance to test at all unfortunately.

**Comment by schofida** [comment]
I got it working finally on 1.0.5a
