### ISSUE TITLE
Defending Major Hold Speak to Fieldco objective not marked as completed.

### ISSUE THREAD

**Issue by schofida** [schofida/CWORR#22]
![image](https://user-images.githubusercontent.com/14967936/226153291-2b11a292-f84d-4e70-bbd8-cc9f07f53245.png)
this appeared i do not remember what hold it was but it will not go away.

**Comment by schofida** [comment]
@LABWAZHERE

Thanks for reporting this. This is the Legate Field CO for Markarth. Defense quests of major holds have this objective to meet with the Field CO. Unfortunately its not getting marked as completed.

**Comment by LABWAZHERE** [comment]
same with the riften one for storm cloaks

**Comment by LABWAZHERE** [comment]
> Defense quests of major holds have this objective to meet with the Field CO. Unfortunately it’s not getting marked as completed.

I will also add that the battle of markarth just boots up without meeting with that general, it just started.

**Comment by schofida** [comment]
Everything reported here should be resolved now in v1.0.6a. Please try again.

**Comment by schofida** [comment]
Marking this as closed. I am unable to reproduce this now
