### ISSUE TITLE
Non objective Map Markers still disappearing during Falkreath Siege battle

### ISSUE THREAD

**Issue by LABWAZHERE** [schofida/CWORR#24]
Battle of Falkreath.     Morthal, Dawnstar Solitude Winterhold and Windhelm all disappear (Winterhold and Windhelm aren't in shot)
![20230319211729_1](https://user-images.githubusercontent.com/128126252/226170878-28d0ac48-e067-4c87-8fd8-d3c76a821d9d.jpg)
![20230319211735_1](https://user-images.githubusercontent.com/128126252/226170881-1b6b9a42-5510-4d4c-af81-bdf8e9aae6e9.jpg)

also occured with Battle of Morthal effected cities were Markarth, Falkreath, Windhelm, Winterhold

**Comment by LABWAZHERE** [comment]
To add to this I think the college of winterhold and dawnstar sanctuary should also have their map markers disabled during a siege

**Comment by LABWAZHERE** [comment]
update: falkreath siege (imperials) now only the minor holds (and sometimes solitude) disappear

**Comment by LABWAZHERE** [comment]
![20230417143937_1](https://user-images.githubusercontent.com/128126252/232379821-a4b6c351-5f44-49ac-9837-e4d55814993a.jpg)
update: markarth siege (imperials) understone keep and markarth stables are not disabled and on top of that all minor hold markers disappear

**Comment by schofida** [comment]
Should be fixed in https://github.com/schofida/CWORR/releases/tag/v1.0.14a
