### ISSUE TITLE
Courier Behaviour Clarification

### ISSUE THREAD

**Issue by LABWAZHERE** [schofida/CWORR#27]
i don't know if this is a bug or not but i have noticed the only places that couriers appear are Markarth stables, Riften stables and Whiterun stables, is that a me issue? or do they only go to those places, I use the fast travel technique, fast travel from Solitude to Riften,  Falkreath to Riften, Riften to Whiterun, Markarth to Riften. i have noticed Falkreath and Katlia's Farm never have the courier appear, is this just bad luck with timing?

also one time i used the horse carriage to travel to another hold and the courier started to talk to me as the screen faded to black and i had to wait a while for him to reappear.

also i have noticed everytime you get a letter from commander, using sky ui it marks them all as being read except for the Last Stand battles and some others  and it also never says letter from commander added 

are these by design or bugs?

**Comment by schofida** [comment]
So one thing I did do is rename the letters (at least what I could do anyway, the letters for defense of minor capitals forts and garrisons are all the same letter) to make them unique so SkyUI should not mark them all as read.

In regards to the Courier, that regrettably boils down to Skyrim's crappy engine. So how the Courier works is that there is a hidden chest where if something gets placed in that chest, it triggers the Courier to take it out and hand it to you. CWO is constructing the letters and placing in that chest. The rest is handled by the Courier AI package (which is TERRIBLE!).
