### ISSUE TITLE
Idea: restoring the escape scenes and final stand not in solitude or windhelm.

### ISSUE THREAD

**Issue by LABWAZHERE** [schofida/CWORR#29]
found this on the cutting room floor site
"City Escape Scenes
Whiterun, Riften, and Markarth's city sieges would have had a scenario where a defending player would fail and be forced to escape the city alongside the Jarl, their Steward, Housecarl, and possibly the local commanding officer (CWEscapeCity). All the Jarls' headquarters (Mistveil Keep, Understone Keep, and Dragonsreach) have escape doors inside of them that would only activate during this scenario, meaning they go unused in the final game. The player would then have to lead the Steward and Jarl through the city with the help of the Housecarl and some friendly soldiers.

While most of the scripting is intact for everything that would happen, only the dialogue for the Whiterun scenario remains in the final game. It's unknown under what circumstances, but Legate Rikke could be the one to say the first line rather than Legate Quentin Cipius."

possibility of adding it, while the whiterun dialouge is the only one intact you could still have the others escape without dialouge, just have rikke say the line. 

and 

"Final Battle not in Solitude/Windhelm

Leftover final battle dialogue suggests the final battle taking place in any of the holds rather than just Solitude or Windhelm." 

don't have to add them just wondering if they could be a cool addition

**Comment by ds-nscorp** [comment]
The CWEscapeCity quest while it is there in the Skyrim records, it is thread bare and would take a ton of work to make it functional. The fact that the voices aren't included for the other Jarls I don't like either. If I get time later, I will see if I can set up something for just Balgruuf.

I like the thematic war ending in Solitude and Windhelm so I think I will keep that. Having the war ending in other holds especially with the Season Unending fixes will make things problematic.

**Comment by LABWAZHERE** [comment]
> The CWEscapeCity quest while it is there in the Skyrim records, it is thread bare and would take a ton of work to make it functional. The fact that the voices aren't included for the other Jarls I don't like either. If I get time later, I will see if I can set up something for just Balgruuf.
> 
> I like the thematic war ending in Solitude and Windhelm so I think I will keep that. Having the war ending in other holds especially with the Season Unending fixes will make things problematic.

what you could do is on full release ask if anybody is up to the task to restore the other escape scenes then add it as a patch for cwo

**Comment by schofida** [comment]
Added to CWO Feature Board https://trello.com/c/Hbazu7bx/39-restoring-the-escape-scenes-and-final-stand-not-in-solitude-or-windhelm

**Comment by LABWAZHERE** [comment]
One way to counter the lack of voice lines (and this is gonna get very crazy) is to use likes like vasnyth or similar mods to recreate voice lines for the other jarls and commanders (a lot of vas in Skyrim voice other characters and use similar voices) so theoretically we could reconstruct them.
Especially considering the fact that the major jarls (Vignar,Laila,Maven and igmud) all have quests related to them so they may have enough lines to recronstruct something (thongvor doesn’t have as many lines as the others) 
but I have no idea how it works or how to utilise it

**Comment by Eve-Knight** [comment]
xVASynth produces such low quality audio that it would be a huge turn off. Would need to be optional at best. ElevenLabs could work well enough, but the voice cloning is a paid feature.

**Comment by LABWAZHERE** [comment]
That sucks

**Comment by LABWAZHERE** [comment]
Some kind of trial run would need to occur to test quality of the lines
