### ISSUE TITLE
Subtitles?

### ISSUE THREAD

**Issue by LABWAZHERE** [schofida/CWORR#31]
Subtitles, do we have any? Or is it just because I use fus ro do’h

**Comment by schofida** [comment]
You should be able to turn Subtitles on in the Skyrim options menu. I have been playing with Closed Caption all the time as I usually am playing muted.

**Comment by LABWAZHERE** [comment]
that's the issue though i have subtitles enabled

**Comment by LABWAZHERE** [comment]
i think this is a compatibility issue with fus ro duh
