### ISSUE TITLE
Siege of Whiterun (imperials) barriers won’t respawn

### ISSUE THREAD

**Issue by LABWAZHERE** [schofida/CWORR#32]
Inside Whiterun hold after lowering the drawbridge and entering Whiterun the barriers won’t respawn to prevent you from running straight to dragonsreach (they remain broken) 

this was the season’s unending update on a save where I took Whiterun as a stormcloak then betrayed Ulfric

**Comment by schofida** [comment]
This is a known issue that I might do as a feature later. Unfortunately barriers don't repair on their own and need to be repaired via scripting. And the quest that keeps track of everything during the city interiors for Whiterun, Riften, and Markarth (CWAttackCity) don't have any reference aliases for the barricades.

**Comment by schofida** [comment]
Added to CWO Feature Board https://trello.com/c/qWda4rj8/40-siege-of-whiterun-imperials-barriers-wont-respawn
