### ISSUE TITLE
Typo in one of your messages

### ISSUE THREAD

**Issue by LABWAZHERE** [schofida/CWORR#33]
I don’t remember which one (not at pc atm) but one of the set up messages for the sieges and missions has a typo it says pleae instead of please (seasons unending update)

**Comment by LABWAZHERE** [comment]
edit:
photo for illustration but it is one of those messages
![20230401134021_1](https://user-images.githubusercontent.com/128126252/231365020-451bf401-288b-4316-90b8-20b9cbf25fbd.jpg)

also radiant not radient
![20230401134016_1](https://user-images.githubusercontent.com/128126252/231451155-5f065533-2f26-4cc3-a27f-0884ff4e1b18.jpg)

**Comment by schofida** [comment]
Fixed in v1.0.6a
