### ISSUE TITLE
invincible solider 

### ISSUE THREAD

**Issue by LABWAZHERE** [schofida/CWORR#35]
Sometimes when doing major siege missions there is one invincible enemy solider. I encountered it in the Markarth offence siege (imperial side) they were in the top where the lever is to open the gates, i have encountered it in other sieges but i don't remember which. 

This isn't a conflict with any of my mods i have as none of them would do this.

**Comment by schofida** [comment]
I will check. I restored some non-respawning defenders that Bethesda cut for some reason. Maybe one is marked as essential?

**Comment by schofida** [comment]
I was not able to find this soldier. If you see again, can you pop the console and select it and send a screenshot of it so I can see the Reference ID?

**Comment by schofida** [comment]
I think that this is fixed in https://github.com/schofida/CWORR/releases/tag/v1.0.10a. See #85
