### ISSUE TITLE
Question about field co's

### ISSUE THREAD

**Issue by LABWAZHERE** [schofida/CWORR#36]
So like is there cut dialogue for the other field commanders or just Rikke and Galmar. It just seems like they are supposed to play a bigger role and that Rikke is not meant to have as big of a role. I just want to know if they have cut dialogue or something.

**Comment by schofida** [comment]
Unfortunately no. The voice files to dole out the quests are only said by Rikke/Galmar (I imagine that was done by Bethesda due to money/laziness)
