### ISSUE TITLE
Promotion dialogue is missing 

### ISSUE THREAD

**Issue by LABWAZHERE** [schofida/CWORR#38]
Tullius doesn’t promote you after successful sieges, i was reminded of this as after the defence of solitude he promotes you and it makes me feel like he isn’t satisfied with my performance. :(

Also on related note, about choosing which hold comes next I know you said it doesn’t make sense for a random solider to suggest holds to retake next however a tribune or legate definitely would have enough authority/respect from Tullius to be able to suggest holds without being deemed insubordinate. so you could make it so that when you get quaestor you can suggest holds however it would not have a 100% success rate or you could add a speech check that won’t be successful unless you have 100 speech. 

But again you don’t have to add that this is just my thoughts on how such a mechanic could Theoretically be added.

**Comment by schofida** [comment]
Can you let me know how many holds that you have control over? Tullius/Ulfric only grants rewards once your side controls 5+ holds.

**Comment by LABWAZHERE** [comment]
> Can you let me know how many holds that you have control over? Tullius/Ulfric only grants rewards once your side controls 5+ holds.

i had like 3 but even then he doesn't promote you when you get 5+ cause when he promotes you he is meant to give you an item and i never got items from him. another thing of note is that in ocw he just promotes you even if whiterun and solitude are your last remaining holds and you take back just one idk if that is just the mod or if that's what was meant to happen.


oh also i forgot but in the original cwo mod tullius/Ulfric gave you a weapon when betraying the opposing team, this wasn't re implemented with the seasons unending update

**Comment by ds-nscorp** [comment]
> i had like 3 but even then he doesn't promote you when you get 5+ cause when he promotes you he is meant to give you an item and i never got items from him. another thing of note is that in ocw he just promotes you even if whiterun and solitude are your last remaining holds and you take back just one idk if that is just the mod or if that's what was meant to happen.

Can you send me a screen of the CWO Debug MCM? I am not quite sure what you mean.

> oh also i forgot but in the original cwo mod tullius/Ulfric gave you a weapon when betraying the opposing team, this wasn't re implemented with the seasons unending update

I have not created a release for this yet but I added this yesterday :)

**Comment by LABWAZHERE** [comment]
what i mean is in simtams mod tullius can promote you without the 5 hold requirement.

this is what the wiki says
![Screenshot 2023-04-17 101152](https://user-images.githubusercontent.com/128126252/232351658-c78bcc16-e81d-42d8-b18d-341947412a08.png)
considering the fact that in open civil war you can break the normal quest by going non linearly (the non base game way) he still promotes you without doing those secondary requirements and additionally he can promote you by retaking your claimed territory

additionally when he talks to you he says things like auxiliary or tribune. 
![20230417195720_1](https://user-images.githubusercontent.com/128126252/232456219-f64094da-58eb-41b0-8a6a-055e963a73df.jpg)

(example)

I believe these moments in tullius's dialogue
![20230417100836_1](https://user-images.githubusercontent.com/128126252/232351954-8aa0de29-21fd-4446-a374-ec95b2a92c1d.jpg)
is where the promotion is meant to be as after saying we now hold____ then saying "i now promote you _____" 
 
here is the full dialogue (this is the first time in save that i have been promoted)
so he will say something like this
![20230418151502_1](https://user-images.githubusercontent.com/128126252/232677682-1dd527b7-8b33-47a6-a0e5-fc3906856d8e.jpg)
Then all this
![20230418151236_1](https://user-images.githubusercontent.com/128126252/232677587-75511c7a-3d6f-46f9-badb-3343579bdbef.jpg)
![20230418151246_1](https://user-images.githubusercontent.com/128126252/232677591-9ab68088-3a0a-4f49-a1df-b1b2bd68367c.jpg)
![20230418151251_1](https://user-images.githubusercontent.com/128126252/232677597-8b0ae9f0-614e-4b62-b825-b026050a379d.jpg)


What i am saying is 
1. this dialogue doesn't appear, when it is supposed to currently it only activates upon successful defence of solitude (not guaranteed) and after taking the last hold before Windhelm. 
2. like seasons unending there was not meant to be a hold restriction originally
3. This dialogue and reward system does not activate at all meaning this entire part is unrestored.
4. this system could be an immersive way to incorporate choosing which hold is taken next as when he promotes you to tribune you'd have enough respect and authority to suggest holds.


he promotes you like this in the base game also.
i don't remember if Ulfric does it in cwo either as the last major time i actually paid attention to a stormcloak run was in my pre pc days during January

i'll start up a stormcloak run now to test it

**Comment by LABWAZHERE** [comment]
also it is interesting to point out that soliders also sometimes have radiant dialogue mentioning your rank

**Comment by LABWAZHERE** [comment]
i just realised this could be a result of swapping sides since the pre requisite quest is joining the legion which you never get when betraying Ulfric or Tullius

**Comment by schofida** [comment]
So here is how the promotions are supposed to work.

So when you first start, the Imperials own (technically) 5 holds and the Stormcloaks own 4. If the Imperials successfully defend or stormcloaks successfully conquer Whiterun, then your side owns 5 holds and you gain a rank and get a reward. From there, it doesn't matter the order. All that matters is what rank you are and how many holds your sides owns.

Rank < 1 and Holds >= 5 (then rank 1)
Rank  = 1 and Holds >= 6 (then rank 2)
Rank = 2 and Holds >= 7 (then rank 3)
(Rank = 3 and Holds = 8) OR Win the war (then rank 4)

This has been working fine for me. But I have also never switched sides. It should not matter but I could be missing something.

**Comment by LABWAZHERE** [comment]
it could be that, maybe getting promoted on the stormcloaks then switching side  for some reason either transfers ranks to imperials or breaks the promotion

**Comment by LABWAZHERE** [comment]
because remember i made the imperials lose all holds then i activated seasons unending

it could be similar to the morthal/winterhold restrictions for seasons unending by which i mean there could be something restricting this dialogue appearing when switching sides

**Comment by LABWAZHERE** [comment]
i think promotion is directly tied to the Joining the imperials or stormcloaks quests, it may be worth if possible to somehow make those quests play beforehand

**Comment by ds-nscorp** [comment]
> because remember i made the imperials lose all holds then i activated seasons unending

It's this then. That Cwrank is a singular variable that is used by both sides that I am pretty sure does not reset once you switch sides.... But it could 👹

**Comment by LABWAZHERE** [comment]
> It's this then. That Cwrank is a singular variable that is used by both sides that I am pretty sure does not reset once you switch sides.... But it could 👹

one thing important thing to note is in one save i was promoted to tribune by tullius (equivalent to Snow-hammer for stormcloaks) after the successful defence of solitude however i should have theoretically already been tribune after taking the second last hold from the imperials before activating seasons unending. so i don't know why i was promoted again.


so my question is why was i promoted to tribune when i theoretically already was

on an unrelated note can i just say how weird the stormcloak ranks are

i mean 
unblooded?
ice veins?
bone - breaker?
Snow hammer?
Stormblade?

if they are trying not to paint themselves as the bad guys then they are doing a terrible job.

**Comment by schofida** [comment]
I will put in a change to reset the rank if you change sides. That should clear things up a little clearer. Keep in mind, you have to talk to the General to actually advance the rank. Which may compound matters if you start Season Unending before talking to the general. It looks like Season Unending throws a giant monkey wrench into this whole system.

As for the stormcloak ranks, yeah, they are kinda goofy lol.

**Comment by schofida** [comment]
I fixed it so now if you switch sides, the CW current rank resets to 0.

**Comment by LABWAZHERE** [comment]
it doesn't work on older saves but that makes sense
