### ISSUE TITLE
Legate rikke has vanished

### ISSUE THREAD

**Issue by LABWAZHERE** [schofida/CWORR#40]
Legate rikke has disappeared from whiterun imperial camp
![20230416194339_1](https://user-images.githubusercontent.com/128126252/232290984-60583597-2764-4261-8bdd-3ec6bea028ef.jpg)
like this except she is meant to be there. this happened twice (changed saves since i thought i was hostile to imperials after accidentally hitting them in the battle of fort greymoor but was just wearing a whiterun curiass in prep for Whiteruns liberation of Vignars tyranny)
anyway both times she disappeared it might be an issue with the fort greymoor battle.
and no she isn't at solitude
![20230416195322_1](https://user-images.githubusercontent.com/128126252/232291535-adbd3584-2e2e-47f5-91ad-990f42dabf28.jpg)

additionally there is no map marker

**Comment by LABWAZHERE** [comment]
update: she was behind the tent for some reason, both her and cipus

**Comment by schofida** [comment]
I will take a look. I don't think that Bethesda put the markers for the Whiterun camps in the right place (since it's never a thing in Vanilla). Not sure why Cipius is there though.

**Comment by LABWAZHERE** [comment]
> Not sure why Cipius is there though.

he is meant to be in the camp since he is the whiterun general he just isnt going into the camp

**Comment by schofida** [comment]
This should be fixed now. Forced her to marker on load so she doesn't appear behind the tent https://github.com/schofida/CWORR/releases/tag/v1.0.15a
