### ISSUE TITLE
Feature idea: add a patch for cloaks of skyrim

### ISSUE THREAD

**Issue by LABWAZHERE** [schofida/CWORR#43]
specifically this one:
https://www.nexusmods.com/skyrimspecialedition/mods/6369
cloaks of skyrim adds cloaks to the game some of which have imperial and hold logos on them. i believe it would be cool if you could add a patch that makes it so if you wear a cape of a stormcloak controlled hold in an imperial hold it does the same thing as the curiass 

same concept with the imperial cloak (this mod is the one that has imperial capes in it hence why i specified it. DO NOT CONFUSE FOR CAPES AND CLOAKS OF SKYRIM OR CAPES OF SKYRIM but you can add patches for those as well if you wish)

**Comment by schofida** [comment]
I actually had this in my CWO Feature Board. https://trello.com/c/170fiiqd/27-allow-cos-cloaks-to-apply-disguise-flags Someone else recommended I do this as well :) I am hoping that someone else can make a patch for this. I never liked capes. I was one probably the only person that was happy when From Software added the feature to hide capes on Armor Sets in Elden Ring.
