### ISSUE TITLE
Battle music sometimes won't stop

### ISSUE THREAD

**Issue by LABWAZHERE** [schofida/CWORR#44]
the battle music sometimes doesn't stop even on qtd and qtm the save itself is stuck with it until i do something that causes it to not do that. is that a you issue or Skyrim issue?

**Comment by schofida** [comment]
Lol this is a classic Skyrim Civil War bug. This must mean that the Civil War siege is still running for some reason. You usually can teleport somewhere else to get it to stop. I also put something in the 'Get CWO Unstuck' MCM option to stop the music. Let me know if either of those work.

**Comment by LABWAZHERE** [comment]
teleporting never works and mcm menu i think but i'll have to confirm it tomorrow

**Comment by schofida** [comment]
Can send me a screen of the CWO Debug MCM?

**Comment by LABWAZHERE** [comment]
i am not at my computer at the moment so i am unable to but when i will when i do

**Comment by LABWAZHERE** [comment]
![20230421171804_1](https://user-images.githubusercontent.com/128126252/233568030-32139bd9-8bd3-4850-b543-b66d126a6ddb.jpg)
(stormcloak save)

**Comment by Eve-Knight** [comment]
My music is still stuck from taking Morthal for the Stormcloaks. The debug MCM says it thinks I'm in Haafingar even though I'm in Eastmarch. I don't see an option in the menu to stop the music.

Fast traveling many places does not resolve. Talked to Ulfric, successfully got next quest, but music still going. Fast traveling many other places still does not end music.

**Comment by LABWAZHERE** [comment]
Did you do fix quest?

**Comment by LABWAZHERE** [comment]
Also if you don’t mind me asking what country are you from, I can’t tell if you are from around Australia/Britain or if you’re just an American with a very scuffed sleep schedule

**Comment by Eve-Knight** [comment]
The "help quests get unstuck" option does end the music. It also seemed to skip forward a bit, though. Not sure if I was supposed to do more than take one fort before Solitude.

I'm in the USA.

**Comment by Eve-Knight** [comment]
Okay, I reloaded and see that it only skipped over Galmar giving me money and telling me about the next quest. So I did that and THEN did the unstuck option and all seems good now.

**Comment by LABWAZHERE** [comment]
> The "help quests get unstuck" option does end the music. It also seemed to skip forward a bit, though. Not sure if I was supposed to do more than take one fort before Solitude.

you are, please lose the battle of solitude for me :)


> I'm in the USA.

wow, what time is it for you, it is 8am here

**Comment by LABWAZHERE** [comment]
> Okay, I reloaded and see that it only skipped over Galmar giving me money and telling me about the next quest. So I did that and THEN did the unstuck option and all seems good now.

I thought ulfric was the guy who reluctantly pays you

**Comment by Eve-Knight** [comment]
It's 6 PM. Galmar does most of the paying. No apparent reluctance.

**Comment by LABWAZHERE** [comment]
> It's 6 PM. Galmar does most of the paying. No apparent reluctance.

I don’t think that is meant to happen unless it is the one time payment from winning sieges, as ulfric usually pays you when you ask for pay and try’s to swindle you out of it by “donating” it to the “cause”

**Comment by LABWAZHERE** [comment]
> it’s 6pm

Ah I see 6pm not too late then, is that east coast or west?

**Comment by Eve-Knight** [comment]
I've never heard any dialogue along those lines. East.

**Comment by LABWAZHERE** [comment]
> Okay, I reloaded and see that it only skipped over Galmar giving me money and telling me about the next quest. So I did that and THEN did the unstuck option and all seems good now.

Okay cool that’s what is meant to happen minus the lack of money.

**Comment by LABWAZHERE** [comment]
> I've never heard any dialogue along those lines. East.

Have you spoken to Ulfric? I usually do a stormcloak traitor route and every time I report back to him when you ask for your pay he says “are you sure?” Whereas Tullius is like I got you fam

**Comment by Eve-Knight** [comment]
Yes, I've spoken to Ulfric. There's never an option to ask for pay. It's simply given.

**Comment by LABWAZHERE** [comment]
> Yes, I've spoken to Ulfric. There's never an option to ask for pay. It's simply given.

okay that’s not normal, Ulfric specifically is supposed to give you an option radiantly when you come back to ask for pay (post siege captures don’t count as pay is always given for that)

**Comment by LABWAZHERE** [comment]
> Okay, I reloaded and see that it only skipped over Galmar giving me money and telling me about the next quest. So I did that and THEN did the unstuck option and all seems good now.


Quote replying to this to “pin this” so that it can be found easier

**Comment by Eve-Knight** [comment]
Music also stuck after winning Solitude. Trying the unstuck option there gave a message about trying to set up the final siege (which was already completed), ended the music, but then started it again.

**Comment by Eve-Knight** [comment]
I also notice my follower was missing, probably because she's the Solitude housecarl. Unstuck made her reappear where I had fast traveled to but still doesn't seem a suitable workaround in this case.

**Comment by Eve-Knight** [comment]
The console command to manually stop the music (both ran directly and via the unstuck MCM) just result in the music instantly restarting for me. Also no resolution from traveling, additional combat, console command to kill player, or relaunching game.

**Comment by LABWAZHERE** [comment]
> The console command to manually stop the music (both ran directly and via the unstuck MCM) just result in the music instantly restarting for me. Also no resolution from traveling, additional combat, console command to kill player, or relaunching game.

The issue is save based, if it happens and you save it there, that save will have the issue, other saves do not

**Comment by LABWAZHERE** [comment]
> The console command to manually stop the music (both ran directly and via the unstuck MCM) just result in the music instantly restarting for me. Also no resolution from traveling, additional combat, console command to kill player, or relaunching game.

Unstuck quest both works and doesn’t work at the same time, it is finicky

**Comment by Eve-Knight** [comment]
I did have a save from before the entire battle. Repeated it and found that upper door. Worked normally there except music still stuck.

**Comment by LABWAZHERE** [comment]
update: button worked the first time in solitude but failed in my older stormcloak save

**Comment by LABWAZHERE** [comment]
update update: it works too well it disables it and it doesn't reactivate on new siege

**Comment by LABWAZHERE** [comment]
update update update: button works

**Comment by LABWAZHERE** [comment]
button is very finnicky sometime it works straight away sometimes the music loops for a bit then stops

**Comment by schofida** [comment]
> button is very finnicky sometime it works straight away sometimes the music loops for a bit then stops

This is unfortunately an engine thing. I cannot do anything about this unfortunately
