### ISSUE TITLE
false front for riften?

### ISSUE THREAD

**Issue by LABWAZHERE** [schofida/CWORR#45]
it didn't happen for me when taking riften is it optional?  on another note is there a false front for a stormcloak or imperial riften and markarth? 
also does stormcloak whiterun have a quest like that? and do the others have quests like that?

**Comment by schofida** [comment]
All Civil War missions are (slightly) randomized now. False Front is only given at Riften for Imperials and at Markarth for Stormcloaks. However, at Riften you may also get a Sabotage mission, Skirmish or Fort siege battle. Setting the number of phases to 5 will (once it works) increase the chance of getting A False Front. You can also turn new quests off in the MCM.

I am thinking of making a change to ensure that you always get the hold specific mission if the number of phases is set 5.

**Comment by LABWAZHERE** [comment]
> I am thinking of making a change to ensure that you always get the hold specific mission if the number of phases is set 5.

i like this idea cause it makes it more unique also does whiterun have one?

**Comment by schofida** [comment]
Whiterun does not unfortunately. Vanilla does not have a campaign in Whiterun (beyond just the siege battle).

**Comment by schofida** [comment]
Closing issue. Re-arranged quests so that now you can potentially get the hold specific mission and fort siege battle (which happens in Vanilla for Markarth and Riften)
