### ISSUE TITLE
Fort battles not working

### ISSUE THREAD

**Issue by LABWAZHERE** [schofida/CWORR#47]
same issue as kastav for stormcloaks, rikke mentions it 
![20230417195513_1](https://user-images.githubusercontent.com/128126252/232455337-8acdb78b-137d-4ca8-b506-dcbccabd081d.jpg)
![20230417195518_1](https://user-images.githubusercontent.com/128126252/232455777-f8bb2ded-ce83-4f39-8891-734a37bd14cc.jpg)

(that setting up missions was a false positive)
but doesn't actually issue the quest

**Comment by LABWAZHERE** [comment]
update: it works again idk how  or why might be on my end but still worth looking into

**Comment by LABWAZHERE** [comment]
also fort neugrad

**Comment by LABWAZHERE** [comment]
if this is a mod conflict on my end i have no clue what is causing it as i do not have conquest installed atm and with almost 130 mods active i'll never be able to pin point it

**Comment by LABWAZHERE** [comment]
this isn't an issue for all forts the follow offence fort missions work without any issue for imperials: fort greenwall, fort greymoor fort kastav, fort dunstad, fort snowhawk (unsure about this one)

i assume fort Amol will work since it is a requirement befort taking windhelm

**Comment by LABWAZHERE** [comment]
i have not tested stormcloak side but i assume these still apply this was in a save where i swapped sides if that helps

**Comment by schofida** [comment]
I created experimental release https://github.com/schofida/CWORR/releases/tag/v1.0.7a to resolve.

This release laxed the dialogue conditions for the fort sieges. Please check if you get the prompt this time. Also make sure to speak with the Rikke/Galmar again after accepting the missions. I want to ensure that they do not try to give you the Fort siege quest again.

**Comment by LABWAZHERE** [comment]
Fort Snowhawk (imperials) didn't boot but that was my current campaign so might have been that. Fort Kastav (imperials) was already a working fort battle (stormcloak is the broken one) gonna wait for markarths fort to see if it will function

**Comment by LABWAZHERE** [comment]
okay new update, it works now the only issue is Rikke lacks some dialogue (she gave me both kill commander and take fort Snowhawk)

**Comment by schofida** [comment]
Can you let me know if this continues to be a problem. I re-arranged the quests so hopefully they work. Also, can you let me know if you skipping passed the dialogue quickly? I normally don't do that but that could be part of the problem, I am setting stuff mid-dialogue to prevent issues like #49 from happening.

**Comment by LABWAZHERE** [comment]
i don't think this is related to this issue but with fort commanders installed battle for fort neugard wasn't given to me, which was one of the trouble forts

**Comment by ds-nscorp** [comment]
Understood. That issue is still open. I need to do more testing.
