### ISSUE TITLE
Duplicate reporting for duty

### ISSUE THREAD

**Issue by LABWAZHERE** [schofida/CWORR#49]
![20230418123148_1](https://user-images.githubusercontent.com/128126252/232655333-6f83ac88-d3ff-4a61-9dcd-5d2526862c39.jpg)
![20230418123219_1](https://user-images.githubusercontent.com/128126252/232655343-dcc6d24b-5525-4e38-a5d8-2d7b1b8a75e6.jpg)
![20230418123230_1](https://user-images.githubusercontent.com/128126252/232655350-7ff3bc97-a7a4-4666-86e0-99eacc90ff5e.jpg)

additionally gave me a double up quest

**Comment by schofida** [comment]
This is most likely due to the fort siege dialogue changes. I will try to put in a fix tonight.

**Comment by schofida** [comment]
Closing issue. This was a symptom of something that I was trying with v.1.0.7.a
