### ISSUE TITLE
Whiterun drawbridge animation

### ISSUE THREAD

**Issue by LABWAZHERE** [schofida/CWORR#52]
This is cursed
![20230418125743_1](https://user-images.githubusercontent.com/128126252/232666072-d42f8c76-c278-4ba1-bb6d-ce5ad9b77e37.jpg)

**Comment by schofida** [comment]
I think that I May? have this fixed. Should be pushing a new release soon.

**Comment by LABWAZHERE** [comment]
![20230428094555_1](https://user-images.githubusercontent.com/128126252/235013548-b05543cf-24f1-4661-aa5c-af10f237a4db.jpg)
still occurs

**Comment by LABWAZHERE** [comment]
the issue is the fake non stationary bridge thing is being placed over the normal lever

**Comment by schofida** [comment]
I have not been able to reproduce. Did you happen to add any town or city mods mid-save? I have heard that something like this could happen with that.

**Comment by LABWAZHERE** [comment]
maybe? i dont think so

**Comment by schofida** [comment]
I'm going to close this. I unfortunately was not able to reproduce
