### ISSUE TITLE
Forts still have bandits

### ISSUE THREAD

**Issue by LABWAZHERE** [schofida/CWORR#53]
it might be good to do what ocw does and have the forts be taken over by their factions troops out of the gate
(or in Whiteruns case Whiterun guards) rather than when the taking the fort quest is active.

so we don't have things like this happening during fort sieges
![20230418123824_1](https://user-images.githubusercontent.com/128126252/232666399-c1ca023e-fdb7-4ca3-ac2c-fc3308e7e77c.jpg)
![20230418123840_1](https://user-images.githubusercontent.com/128126252/232666582-650f89d8-f441-446a-8e3f-09e245cf4f56.jpg)

additionally on the topic of Ocw 

that mod uses yellow flags for whiterun faction on war maps 

before they align with the imperials

was that just a ocw addition? 

cause if it isn't i think that would be cool to restore if 

it is an ocw thing don't worry about it

**Comment by schofida** [comment]
I think I have a fix for the spawns still persisting in the fort siege. I should have a release tomorrow I hope.

**Comment by schofida** [comment]
This should be fixed going forward. I will close this for now. Let me know if this continues to happen
