### ISSUE TITLE
more specific siege dialogue

### ISSUE THREAD

**Issue by LABWAZHERE** [schofida/CWORR#55]
is it possible to restore more specific siege dialogue when the co says we're taking the capital

i know it exists cause rikke says it when taking winterhold and riften
example:
![20230417143923_1](https://user-images.githubusercontent.com/128126252/232678440-e8783afa-f7ca-4d25-9241-83deb75dbf99.jpg)

instead she says were taking markarth

**Comment by schofida** [comment]
Regrettably no. Since these sieges were never triggered in Vanilla, Bethesda never recorded the lines. :(
