### ISSUE TITLE
 Tulius final speech issues

### ISSUE THREAD

**Issue by LABWAZHERE** [schofida/CWORR#56]
heads looking all over the place (this isn't meant to happen)

 i can see why tullius hates speeches now

![20230418153653_1](https://user-images.githubusercontent.com/128126252/232682134-f728a161-9e12-4deb-9ccb-9c669c6da4d3.jpg)
additionally 
![20230418153631_1](https://user-images.githubusercontent.com/128126252/232682311-66a21fd5-309a-47d3-926c-454b9bd84531.jpg)
![20230429103933_1](https://user-images.githubusercontent.com/128126252/235273560-707f080f-81f2-410f-b7b5-d0349426afba.jpg)
![20230429103935_1](https://user-images.githubusercontent.com/128126252/235273562-2846a7f8-b55d-4b2c-9364-7218685d427f.jpg)

i don't think this is meant to be here usually they are closer and not as far back

**Comment by LABWAZHERE** [comment]
if you didn't understand what i am saying, the speech needs to be adjusted as people aren't looking at tullius

**Comment by LABWAZHERE** [comment]
also his head missaligned when talking to you about this
![20230429104219_1](https://user-images.githubusercontent.com/128126252/235273632-24f9457d-1373-40b2-87bd-74120235506e.jpg)

**Comment by schofida** [comment]
Should be fixed now https://github.com/schofida/CWORR/releases/tag/v1.0.15a
