### ISSUE TITLE
Ralof Conversation Now Broken at Korvanjund for Jagged Crown Quest for Stormcloaks

### ISSUE THREAD

**Issue by Eve-Knight** [schofida/CWORR#57]
Normally, if the player opts to meet with Galmar as instructed rather than charging in and engaging the Imperials, Ralof forcibly starts a conversation with the player as they try to approach Galmar. Now, that conversation seems impossible to activate, even if intentionally trying. Version 1.0.7a.

**Comment by LABWAZHERE** [comment]
have you confirmed if this is also an imperials issue?

I remember in previous versions (v1.0.5a seasons undending update) Ralof still communicates with you as i had started a new save after that. So this would definitely have to be a recent issue

**Comment by LABWAZHERE** [comment]
also are you another tester? if so welcome to the team :D

**Comment by Eve-Knight** [comment]
I have not tried this portion on the imperial side, no.

If downloading the mod and posting here makes me a tester, then yes and thank you. =)

Of course, the ugly third possibility is that it's simply inconsistent. I didn't repeat the process to see if it kept happening.

And the fourth is the ubiquitous threat of conflicts. I'd be happy to check anything specific I should in SSEEdit for conflicts. I couldn't find anything at a glance, though. Ralof himself seems to match except for appearance data.

**Comment by LABWAZHERE** [comment]
>And the fourth is the ubiquitous threat of conflicts. I'd be happy to check anything specific I should in SSEEdit for conflicts. I couldn't find anything at a glance, though. Ralof himself seems to match except for appearance data.

i doubt it is , unless you have a mod that specifically targets that quest or ralof/hadvar themselves i doubt a conflict is likely but it is always good to check

**Comment by Eve-Knight** [comment]
I also doubt it. I found the quest; it's CW02A. Only the unofficial patch touches it. So either it's random engine weirdness or the change is in something other than the NPC or quest.

**Comment by LABWAZHERE** [comment]
> I also doubt it. I found the quest; it's CW02A. Only the unofficial patch touches it. So either it's random engine weirdness or the change is in something other than the NPC or quest.

it might have to do with the bug i pointed out to schofida that for some reason during the battle of markarth and riften ralof and hadvar don't appear for the outside battle, just appear inside mistvil and understone so I assume the 1.07 update has changes to hadvar and ralof in an attempt to fix that

(Whiterun as works fine)

**Comment by schofida** [comment]
Thanks @Eve-Knight for reporting. Sorry for the delayed response. Work has been crazy this week. I found the dialogue record [INFO:000E6C33]. CWO does not change this record or affect CW02A or CW02B. Also, as @LABWAZHERE  reported, I made some adjustments but that's only to the CWAttackCity quest and it should have no bearing on the Jagged Crown. I do see in my load order that this record is overridden by Alternate Start Live Another Life. I will try to take a look tonight to see if I can reproduce.

**Comment by Eve-Knight** [comment]
My pleasure. Thank you for all your efforts on the mod, too.

I'm actually not even using any alternate start. Makes sense regarding Live Another Life, though; it removes references to Helgen since you aren't there, and knowing Ralof already would be such a reference.

That still leaves us no closer to knowing what caused this, of course.

**Comment by schofida** [comment]
It sounds like you were able to get around this issue. What were you able to do?

I tried to replicate last night but I was unable.

**Comment by Eve-Knight** [comment]
I was, yes. The issue was never blocking as the Jagged Crown quest doesn't really rely on talking to Ralof. It's just extra flavor. Galmar acted normally and charged in as usual after his speech.

**Comment by LABWAZHERE** [comment]
i'd just like to add i could not replicate this, in my stormcloak save pre  jagged crown he ran up to me
![20230422173420_1](https://user-images.githubusercontent.com/128126252/233770168-6d63140c-8dc3-489b-8c37-03ebf0a83f34.jpg)

**Comment by LABWAZHERE** [comment]
it is also interesting to point out that (even in base game) no matter who you choose to go with (hadvar or ralof) both of them will appear id you join opposing sides (ralof if you went with hadvar and joined stormcloaks and hadvar if you went with ralof and joined the legion)

**Comment by schofida** [comment]
I going to close this issue but I will see if I can do more digging sometime to see if this is a general Skyrim bug and how they resolved.
