### ISSUE TITLE
commander caius doesn't leave the bannered mare after imperials reclaim whiterun 

### ISSUE THREAD

**Issue by LABWAZHERE** [schofida/CWORR#61]
![20230422165623_1](https://user-images.githubusercontent.com/128126252/233768259-3604a5e2-28bc-4f6b-afa7-c555834e4a2c.jpg)
he is meant to be wearing whiterun guard outfit and be walking around whiterun

**Comment by schofida** [comment]
This is also probably another Skyrim bug but I will take a look.

**Comment by schofida** [comment]
This was a pain. Vanilla Skyrim did nothing. USSEP did something but it was only a one and done thing. I have not tested but I think that this should be fixed in https://github.com/schofida/CWORR/releases/tag/v1.0.11a
