### ISSUE TITLE
(imperials) defence battle of windhelm somehow triggered by fix quest

### ISSUE THREAD

**Issue by LABWAZHERE** [schofida/CWORR#62]
uh
![20230422170909_1](https://user-images.githubusercontent.com/128126252/233769366-780637f4-e2c9-451a-ba24-a9cbb1159eff.jpg)
uh?
![20230422171004_1](https://user-images.githubusercontent.com/128126252/233769370-15d35677-005f-44b2-97cf-0fb439f00445.jpg)
UHHHH?
![20230422171017_1](https://user-images.githubusercontent.com/128126252/233769380-afe12bc3-5442-4d6e-aecd-cee9118c21c0.jpg)
![20230422171041_1](https://user-images.githubusercontent.com/128126252/233769398-d079ddfb-cbb1-40da-98f1-c1eb952500ed.jpg)
![20230422171126_1](https://user-images.githubusercontent.com/128126252/233769401-e3d375f9-ddbb-44e5-acd5-d9efbaa011e6.jpg)
![20230422171447_1](https://user-images.githubusercontent.com/128126252/233769403-ff35a6c2-c2ee-489b-9b58-518e47deb950.jpg)
UHH
![20230422171455_1](https://user-images.githubusercontent.com/128126252/233769407-6d173b07-efc8-4a89-b344-0f38f0406e1d.jpg)
HHHHH

i am just now realising you probably don't speak uh, so allow me to translate
basically while in dragonsreach i tried to do the thing you suggested to fix the music (help quest get unstuck, i did this at castle dour and it worked) and instead of saying nothing to fix it said attempting to set up siege, now for clarification
![20230422172243_1](https://user-images.githubusercontent.com/128126252/233769704-d61d95be-9c16-449b-96e3-07425d858c49.jpg)
these were my holds beforehand

now after it said setting up siege nothing happened so i did it again then across my screen appeared the words
STARTED: BATTLE OF WINDHELM
speak to the imperial
then after that i opened the mcm and saw this
![20230422171447_1](https://user-images.githubusercontent.com/128126252/233769783-4faa1b93-0a71-45c1-8786-be1959056ab5.jpg)
and afterwards when i intentionally lost to see what would happen it said i had completed it for the imperial as well

i am very confused
is this a bug?

**Comment by ds-nscorp** [comment]
Are you sure you didn't click 'win the war' by mistake? It looks like that's what happened. I will take a look to make sure that that routine didn't fire by mistake. That 'win the war' option is something left over from the old CWO is something I didn't test yet.

In the meantime, can you show me the MCM of what the state of the war before pressing the 'get CWO unstuck'? I'm trying to pin down why the music is still playing

**Comment by LABWAZHERE** [comment]
that was the state shown in the above mcm menu (whiterun one, that is the same point that i was at just outside dragonsreach that was a save in which i didn't disable battle music and instead got a whiterun defence mission

**Comment by LABWAZHERE** [comment]
Additionally winning the war at least if you aren’t allied with a side doesn’t start a siege it just stops the cw in its tracks but even that doesn’t explain why it was a defence mission instead of offensive, I have never seen ulfric run at windhelm with such conviction before

**Comment by schofida** [comment]
So I found a serious bug with the 'Get Quest Unstuck'. I think that I fixed it now in v1.0.8a. Can you try again?

**Comment by LABWAZHERE** [comment]
okay
