### ISSUE TITLE
Lex Iustificati Enchantment Oddities

### ISSUE THREAD

**Issue by Eve-Knight** [schofida/CWORR#63]
1. Text on item now shows a banish daedra effect. In reality, it looks like its effects are this plus the effect of Dawnbreaker and Call to Arms.
2. The sword can be disenchanted. Doing so learns the Dawnbreaker effect only.
3. When the sword fires off Call to Arms, it increases the player's illusion skill. This happens even if the sword is being used by the player's follower and not the player themselves.

**Comment by ds-nscorp** [comment]
Thank you for finding this. Some of the enchants are kind of whack. I have been fixing them as I found them. I will take a look at this.

**Comment by schofida** [comment]
This is fixed in https://github.com/schofida/CWORR/releases/tag/v1.0.10a It now displays what it actually does. And disenchanting should yield the same enchantment

**Comment by Eve-Knight** [comment]
Okay, got the new version. Its description reads:

When, you defeat an enemy, there is a chance of boosting your allie's Weapon Skills by 25 for 10 minutes.

To improve grammar and spelling, I'd recommend:

When you defeat an enemy, there is a chance of boosting your allies' weapon skills by 25 for 10 minutes.

**Comment by LABWAZHERE** [comment]
I don’t think allies needs an apostrophe cause allies suggests multiple cause doing allies’ suggests it is Allies who is Allie? Or alternatively Allys’ but that isn’t a word

**Comment by Eve-Knight** [comment]
If it boosted just one ally, it would be ally's. I'm pretty sure it's any nearby allies, though. Hence allies'.

**Comment by LABWAZHERE** [comment]
But allies is already plural?

**Comment by LABWAZHERE** [comment]
S’ is possessive isn’t it?

**Comment by Eve-Knight** [comment]
Yes, allies is plural but not possessive. It's "allies' weapon skills." If we want to avoid the apostrophe, we'd have to rephrase it as "the weapon skills of your allies" instead.

**Comment by LABWAZHERE** [comment]
Your allies wouldn’t need an apostrophe

**Comment by Eve-Knight** [comment]
The actual object is skills. It's the skills of the allies.

**Comment by LABWAZHERE** [comment]
Why must English have a broken language system

**Comment by LABWAZHERE** [comment]
I honestly am confused myself

**Comment by Eve-Knight** [comment]
If we were to use friend instead, it may be more clear for you.

friend: singular, not possessive
friends: plural, not possessivve
friend's: singular, possessive (for example, "your friend's bag" would refer to a bag belonging to one friend)
friends': plural, possessive (for example, "your friends' bag" would refer to a bag that is shared between multiple friends)

**Comment by Eve-Knight** [comment]
I say this just as a grammar example, of course. In Skyrim, friends and allies are two different entities.

**Comment by LABWAZHERE** [comment]
I thought it was the other way around ‘S for shared S’ for singular

**Comment by Eve-Knight** [comment]
"...your allies's weapon skills..." would also be valid. Since allies ends in S, though, we also have the option of saying "...your allies' weapon skills..." instead.

The only exception that comes to mind offhand of a word that can be made possessive without an apostrophe is "its" to distinguish it from the contraction "it is."

**Comment by Eve-Knight** [comment]
It sounds like rephrasing it to say "the weapon skills of your allies" is our best bet.

**Comment by LABWAZHERE** [comment]
Yes

**Comment by LABWAZHERE** [comment]
English: It just works

**Comment by Eve-Knight** [comment]
As for the rules for the case in point, though, ally is singular and allies is plural. So if we do make it possessive, we have to keep the original word intact. So ally's for singular possessive and your choice of allies' or allies's for plural possessive.

**Comment by LABWAZHERE** [comment]
I thought if it was plural the apostrophe wasn’t required as the word already suggests more than one

**Comment by Eve-Knight** [comment]
The apostrophe would be to make it possessive, not to make it plural.

Ally = singular (no apostrophe)
Allies = plural (no apostrophe)

**Comment by ds-nscorp** [comment]
@LABWAZHERE @Eve-Knight I woke up this morning to 100+ notifications and I almost had a heart attack. Y'all trying to kill me lol!
