### ISSUE TITLE
Helm of the Unknown Legate Effect Description Typos

### ISSUE THREAD

**Issue by Eve-Knight** [schofida/CWORR#64]
Peeking through the data, I see the helm's effect's description is:

Change to turn enemy Eatheral on hit

Change is probably supposed to be "Chance," and "Eatheral" is probably supposed to be "ethereal."

**Comment by ds-nscorp** [comment]
Good catch. Will fix!

**Comment by schofida** [comment]
This is fixed in https://github.com/schofida/CWORR/releases/tag/v1.0.10a I updated the description to how it actually works. It may look a little weird but I had it on for a while and it works pretty well.
