### ISSUE TITLE
sky ui courier not functioning properly again

### ISSUE THREAD

**Issue by LABWAZHERE** [schofida/CWORR#66]
![20230423102848_1](https://user-images.githubusercontent.com/128126252/234154768-2690d502-8199-4581-9a52-8dee50164a53.jpg)
for clarification this is unopened and on a stormcloak save

**Comment by Eve-Knight** [comment]
Mine looked the same. The complaint here is that it's already marked as read even though you haven't read it? I think it's technically the same note since it just has aliases replaced as appropriate. I wonder if the base game's bounty letters have the same issue.

**Comment by LABWAZHERE** [comment]
> Mine looked the same. The complaint here is that it's already marked as read even though you haven't read it? I think it's technically the same note since it just has aliases replaced as appropriate. I wonder if the base game's bounty letters have the same issue.

schofida patched this in an earlier update, i think since he edited some text for it it broke again

**Comment by LABWAZHERE** [comment]
>I wonder if the base game's bounty letters have the same issue.

they don't
source: experience

**Comment by LABWAZHERE** [comment]
letters of inheritance and bounties aren't all marked as read same deal with letters from a friend (greybeards)

**Comment by schofida** [comment]
> schofida patched this in an earlier update, i think since he edited some text for it it broke again

I was able to change the text between the major cities and everything else. But the 'Everything Else' was the same object so I know that they wouldn't truly work. I was hoping to just remove the note programmatically while the siege was going since you no longer need it but Engine Limitations prevent that from working. Since you mention that bounty letters don't do that, maybe I can see how they do it.

**Comment by LABWAZHERE** [comment]
> > schofida patched this in an earlier update, i think since he edited some text for it it broke again
> 
> I was able to change the text between the major cities and everything else. But the 'Everything Else' was the same object so I know that they wouldn't truly work. I was hoping to just remove the note programmatically while the siege was going since you no longer need it but Engine Limitations prevent that from working. Since you mention that bounty letters don't do that, maybe I can see how they do it.

i'd also like to point out that it never says letter from commander added to your inventory, is that possible to do or not?

**Comment by Eve-Knight** [comment]
Somewhere along the way, my "Defending Location Under Attack!" notes have combined into a stack of two in my inventory. I can now only read the most recent one.

**Comment by schofida** [comment]
Can you both check this again? I think I have this mostly fixed going forward. The name of the city/fort/town should be in the note now.

**Comment by Eve-Knight** [comment]
Yeah, I'm starting a new save. So ... provided I get put on the defensive again ... I'll let you know either way.

**Comment by LABWAZHERE** [comment]
It is fixed and says the specific town/fort/city but it still marks all notes as read

**Comment by schofida** [comment]
I will look at this next.

**Comment by schofida** [comment]
I will unfortunately need to add this as a known issue. I cannot get these damn papers to not be marked as read. I will just have to get folks to sell these notes after a siege
