### ISSUE TITLE
Bounty

### ISSUE THREAD

**Issue by Eve-Knight** [schofida/CWORR#67]
Incurred a 3-gold bounty while going to sabotage Stonehills. Maybe it's because the Hjaalmarch Guard joined in the fight. I have a mod preventing me from hitting a friendly target, so it's not an accidental hit.

More so, I tried the MCM option to pay the bounty and it did nothing.

**Comment by LABWAZHERE** [comment]
Is Morthal your enemy?

**Comment by Eve-Knight** [comment]
They were, yes. Thankfully, after taking the entire hold, the script that cleared all the bounties still worked.

**Comment by LABWAZHERE** [comment]
Pretty sure if you’re sabotaging something in stonehills it is because morthal is your enemy

**Comment by LABWAZHERE** [comment]
> They were, yes. Thankfully, after taking the entire hold, the script that cleared all the bounties still worked.

That’d be why. clear bounty only works for friendly holds

**Comment by LABWAZHERE** [comment]
As in it’s function is to clear bounty from windhelm or solitude because you donk up an hit a friendly troop

**Comment by LABWAZHERE** [comment]
> They were, yes. Thankfully, after taking the entire hold, the script that cleared all the bounties still worked.

Wait did you still have a bounty in morthal after capture?

**Comment by Eve-Knight** [comment]
No, it went away when it flipped to friendly.

**Comment by LABWAZHERE** [comment]
Okay cool that’s normal

**Comment by LABWAZHERE** [comment]
I am not sure if this is an issue but keep it open until Schofida gives us the verdict

**Comment by schofida** [comment]
Thanks @LABWAZHERE for fielding this. Yeah, the Clear bounty is something that I use for the Crime Factions for the imperials/stormcloaks that accumulate when you attack your friends by mistake. It does not show up as a 'bounty added to...' so its invisible to the user and its very annoying. I figure that being able to clear Hold bounties would be a bit of a stretch so I will leave it the way it is for now.
