### ISSUE TITLE
Fast Travel to Friendly Capital Disabled

### ISSUE THREAD

**Issue by Eve-Knight** [schofida/CWORR#68]
For battles, the site of the battle has its map marker disabled as expected. However, after the battle is over, I notice that the map markers for my friendly capital where I report the victory to the leader are also disabled. They reappear after I fast travel somewhere, but it still seems wrong. Why are map markers nowhere near the battle being disabled?

**Comment by LABWAZHERE** [comment]
This is a known issue, which side are you? As only the minor battles for imperials disable map markers?

**Comment by LABWAZHERE** [comment]
In addition to this things like dawn dawnstar sanctuary and college of winter hold don’t get disabled either

**Comment by Eve-Knight** [comment]
I'm fighting for the Stormcloaks against the Empire. I think all the battles disable at least the appropriate map markers.

**Comment by LABWAZHERE** [comment]
I have a list of which ones get disabled in which fight in my dedicated bug report of map markers

**Comment by LABWAZHERE** [comment]
But it doesn’t include stormcloak ones

**Comment by schofida** [comment]
Closing this issue. I have not had a chance yet but I will hopefully tackle the map markers soon. Handling under #24
