### ISSUE TITLE
Disguise Options should be flipped

### ISSUE THREAD

**Issue by LABWAZHERE** [schofida/CWORR#69]
I think you should swap the disguise options so that realistic is default and default is original. Cause it is very annoying starting a new game trying to get to seasons unending only to be attacked on site in Whiterun  or Solitude or Riften and their towns just because I chose their enemy by default they shouldn’t know I am a stormcloak or imperial and having to navigate the mcm menu to change it

**Comment by schofida** [comment]
I don't think so. I think that the disguise mechanic works well for the new missions added (at least as good as it could). I agree for testing its kind of annoying (I need to remember to do that as well) but in the long run, you are testing a scenario I believe to pretty niche.
