### ISSUE TITLE
Solitude Battle Locked Door Issue (Cutting Room Floor?)

### ISSUE THREAD

**Issue by Eve-Knight** [schofida/CWORR#70]
Fought to the door to enter the castle but it was locked. Looked around and found a door I could go in for the Thalmor Headquarters (added by Cutting Room Floor). Doing so triggered the dialogue with Tullius and Rikke even though they were in an inaccessible part of the cell. When it got to the point in the script where they become hostile, Ulfric etc. went back outside, so the battle took place out on the castle walls. Otherwise, still worked mostly normally, give or take Galmar being stuck in bleedout animation.

**Comment by LABWAZHERE** [comment]
This is probably due to the last stand of solitude fixes I haven’t gotten last stand of windhelm to work so idk if it works but the proper battle for windhelm as imperials functions perfectly fine

**Comment by LABWAZHERE** [comment]
I’d just like to add that it is a good thing you are doing the stormcloak side as it allows me to focus on the imperials, one thing I do think you should do is intentionally lose the battle of solitude then lose all holds up to windhelm then win and lose windhelm then do the civil war as normal to ensure everything in the stormcloak side functions normally

**Comment by LABWAZHERE** [comment]
Also test switching sides from imperials to stormcloaks during seasons unending and play as an imperial traitor

**Comment by LABWAZHERE** [comment]
Also no this isn’t a cutting room floor thing, I have that installed as well 
( I want to experience the true Skyrim not the one we got)

**Comment by LABWAZHERE** [comment]
Additionally this sometimes applies to Markarths commanders door as that is also sometimes locked
while I don’t think this is a cutting room floor issue it is still worth looking into

**Comment by LABWAZHERE** [comment]
> Fought to the door to enter the castle but it was locked. Looked around and found a door I could go in for the Thalmor Headquarters (added by Cutting Room Floor). Doing so triggered the dialogue with Tullius and Rikke even though they were in an inaccessible part of the cell. When it got to the point in the script where they become hostile, Ulfric etc. went back outside, so the battle took place out on the castle walls. Otherwise, still worked mostly normally, give or take Galmar being stuck in bleedout animation.

question did you try the upstairs door as well?

**Comment by LABWAZHERE** [comment]
There are 2 doors the bottom door and top door, if the bottom door was locked then try the top door

**Comment by LABWAZHERE** [comment]
> Fought to the door to enter the castle but it was locked. Looked around and found a door I could go in for the Thalmor Headquarters (added by Cutting Room Floor). Doing so triggered the dialogue with Tullius and Rikke even though they were in an inaccessible part of the cell. When it got to the point in the script where they become hostile, Ulfric etc. went back outside, so the battle took place out on the castle walls. Otherwise, still worked mostly normally, give or take Galmar being stuck in bleedout animation.

can you try to bleed out in the interior section?
As in inside solitude see what happens and tell us what happens

**Comment by Eve-Knight** [comment]
I went into the Thalmor Headquarters, and that triggered things enough for them to come outside. At that point, they were outside, so no, I did not try any other doors.

Solitude is no longer on fire and people are going about their business as normal. Not sure how I'd manage to bleed out.

**Comment by LABWAZHERE** [comment]
> I went into the Thalmor Headquarters, and that triggered things enough for them to come outside. At that point, they were outside, so no, I did not try any other doors.
> 
> Solitude is no longer on fire and people are going about their business as normal. Not sure how I'd manage to bleed out.

Wait so when you originally went in they were going about their normal business?

**Comment by LABWAZHERE** [comment]
What I mean is after the battle outside solitude the battle inside solitude

1 is it burning if not does it say force Tullius to surrender or something?
2 have you tried the normal 2 doors of castle dour?
3 have you tried bleeding out if point 1 is achieved?

**Comment by Eve-Knight** [comment]
No. They are now, after the battle, traveling away, etc. The quest is completed.

**Comment by LABWAZHERE** [comment]
> No. They are now, after the battle, traveling away, etc. The quest is completed.

Do you have the save to repeat the above points?

**Comment by LABWAZHERE** [comment]
Also send a picture of the mcm menu when you are inside solitude

**Comment by LABWAZHERE** [comment]
I want to make sure this isn’t an issue similar to the battle of Whiterun and Markarth where they don’t function properly additionally the bleed out is to see if it triggers a lose condition or if it triggers the victory scene

**Comment by LABWAZHERE** [comment]
I also want you to download a mod from Bethesda.com called cheat room by bradenm he has a cheat spell which allows you to unlock locked doors, I want you to unlock that locked door and tell me if you can move when you enter castle dour

**Comment by LABWAZHERE** [comment]
This could just be solitude locked door or it could be a bigger issue, we need to rule out the latter before we know it is the former

**Comment by Eve-Knight** [comment]
No, I did not make a save there.

**Comment by LABWAZHERE** [comment]
> No, I did not make a save there.

Damn

**Comment by LABWAZHERE** [comment]
When I get home today I’ll test it with the latest release

**Comment by LABWAZHERE** [comment]
> No, I did not make a save there.

If you encounter issues like this, it is always best to save it so we can test what is going on

**Comment by LABWAZHERE** [comment]
https://github.com/schofida/CWORR/issues/44#issuecomment-1522663493

Related to this topic

**Comment by LABWAZHERE** [comment]
Will test this when I get home

**Comment by schofida** [comment]
@LABWAZHERE @Eve-Knight I'm HERE! :)

I just pushed a release https://github.com/schofida/CWORR/releases/tag/v1.0.8a which makes many changes based on both of your feedback. I will be responding specifically to the issues to let you all know what was addressed tomorrow. I am on East Coast USA. It is 1:30 in the morning and I am very tired :)

**Comment by LABWAZHERE** [comment]
Oof have a good night

**Comment by LABWAZHERE** [comment]
I may not have much time to test this tonight as I wake up at 6am and am unavailable until like 5 or 6 pm, but I’ll test as much as I can

**Comment by LABWAZHERE** [comment]
UPDATE: i after play testing, have determined, this isn't a bug but an intentional feature, it make sense the bottom door would be locked and considering the fact that the upper door has a barricade defending it, this is intentional

what i did determine is that the freeze glitch occured for a bit until the kill scene

**Comment by LABWAZHERE** [comment]
Just add a patch for cutting room floor to lock the thalmor embassy

**Comment by schofida** [comment]
Thank you @LABWAZHERE for testing. Will close
