### ISSUE TITLE
Losing battle of solitude (stormcloak) in the exterior phase doesn't properly shut down the battle

### ISSUE THREAD

**Issue by LABWAZHERE** [schofida/CWORR#73]
![20230426194812_1](https://user-images.githubusercontent.com/128126252/234538837-79d70b0a-50fa-4e79-9104-121160f235c7.jpg)
![20230426194804_1](https://user-images.githubusercontent.com/128126252/234538864-56c9c72c-8703-47a3-b9fe-fbba5b082568.jpg)
when i first arrived in solitude the battle was raging on as if the exterior was a success

this is it now
![20230426195017_1](https://user-images.githubusercontent.com/128126252/234539197-4b216d45-b932-4ff3-842a-d1a3e13f5f89.jpg)

**Comment by LABWAZHERE** [comment]
additionally the only proper way to lose the battle of solitude is if you bleedout, i think you should be able to lose the outside city phase like any other capital siege, it'd make it more challenging, i mean this is the last stand, their last chance, it shouldn't be an almost guaranteed win

**Comment by LABWAZHERE** [comment]
same concept for windhelm, it is their last stand they should be able to win and push back the imperials

**Comment by schofida** [comment]
> additionally the only proper way to lose the battle of solitude is if you bleedout, i think you should be able to lose the outside city phase like any other capital siege, it'd make it more challenging, i mean this is the last stand, their last chance, it shouldn't be an almost guaranteed win

I don't understand. You said that you lost the battle but the only way to do so is to bleedout? You should be able to lose by losing too many troops just like any other siege. I tested this at Windhelm previously. How did you get the scenario in the city to happen then?

In regards to why the city looked like that, I imagine you hit the defense was successful stage but then you knocked down the last barricade which satisfies the win condition. I can fix this.

**Comment by LABWAZHERE** [comment]
i never saw the attacking troops 100 and defending troops 100 appear on screen so i assumed it wasn't a thing i bled out during the outside solitude stage and when that happened i respawned at the now burning siege camp

**Comment by schofida** [comment]
Can you let me know which camp you get teleported to when you entered bleedout?

So what happens is that the siege unfortunately continues to run even after you lose or win. It waits until you out of the city location to finally stop the quest. If you are still in Haafingar hold when you are whisked away to the camp, the siege will still be running. (I am still adding a fix to the city interior door to block you if the defense wins)

**Comment by LABWAZHERE** [comment]
the one that appears when the siege boots up i think it is literally called solitude siege camp

**Comment by schofida** [comment]
Ah crap. Yeah that's right next to Solitude. Bethesda sure made Haafingar really cramped. I'll fix!

**Comment by LABWAZHERE** [comment]
> I am still adding a fix to the city interior door to block you if the defense wins

you have been banned from Solitude for attempting to give the elves what they wanted. next time get good at the videogame.

 -General Tulius

**Comment by LABWAZHERE** [comment]
And the one for Windhelm would be

You have been banned from Windhelm for not being racist and not falling for my lies

next time be born a nord
Talos guide you

 -Jarl Ulfric stormcloak, Jarl of Windhelm and true high king

**Comment by LABWAZHERE** [comment]
I think in terms of multiplayer game lobbies 

Ulfric is definitely the type of person who would be saying ez even when he is losing while thinking he is the best person on his team and thinking he is doing what’s best for his team  and thinks he is better than the enemy but he is actually undermining his team and is the sole reason his team is losing

Tulius would be the kind of guy who would be sick of everyone’s shit and just wants to do what’s best for everyone on his team and is definitely the best person on his team but has no support from team mates and is getting smack talk from Ulfric even though he is obliterating him and is just hoping he can survive long enough for his team to win 

meanwhile the Thalmor would be gaslighting both sides while hoping Ulfrics side wins because they know they can’t beat Tulius’s team meanwhile tuliuses team is fully aware of this but can’t help tulius because they need to protect the objective 

Edit: I just realised this sums up the political situation of skyrim

**Comment by schofida** [comment]
All of this is great! I feel you probably warrant your version of CWO.

https://github.com/schofida/CWORR/releases/tag/v1.0.10a has the fix that prevents the door from opening. Leaving open as I still need to investigate why bleeding out still put you in Haafingar. You should have been sent to Hjaalmarch.

As an aside, @LABWAZHERE and @Eve-Knight, I will be away for 4-5 days. I will continue with bug-fixing/investigating these issues sometime next week. Thanks again for all of your reports and your continued diligence and patience.

**Comment by LABWAZHERE** [comment]
okay, have fun

**Comment by schofida** [comment]
> Leaving open as I still need to investigate why bleeding out still put you in Haafingar. You should have been sent to Hjaalmarch.

looking at this next.

**Comment by schofida** [comment]
This should be fixed now. You should be sent to a camp in another hold that is enabled now https://github.com/schofida/CWORR/releases/tag/v1.0.15a
