### ISSUE TITLE
some troops still appear after successful siege (imperials)

### ISSUE THREAD

**Issue by LABWAZHERE** [schofida/CWORR#76]
![20230428095521_1](https://user-images.githubusercontent.com/128126252/235014946-81c73c31-36ba-41d6-86b5-9a40344f4441.jpg)
![20230428095530_1](https://user-images.githubusercontent.com/128126252/235014951-60070f55-aed3-48a2-945f-943f4c6acf0d.jpg)

**Comment by schofida** [comment]
I know what this is. Thanks! I'll fix

**Comment by LABWAZHERE** [comment]
also while we are here
![20230417144238_1](https://user-images.githubusercontent.com/128126252/235015447-148a683d-cea6-4e27-a9c0-e500514ecf67.jpg)

do Whiterun versions of these troops exist for imperials?

**Comment by schofida** [comment]
This is fixed https://github.com/schofida/CWORR/releases/tag/v1.0.10a. See #85

And no. Those troops don't exist for imperials :( They just look like regular Whiterun guards.
