### ISSUE TITLE
proper changeover does not occur in whiterun

### ISSUE THREAD

**Issue by LABWAZHERE** [schofida/CWORR#77]
![20230428094828_1](https://user-images.githubusercontent.com/128126252/235015058-1891011b-f1bd-4e50-8eff-b56ea755f165.jpg)
![20230428094835_1](https://user-images.githubusercontent.com/128126252/235015066-381516ec-04ff-45eb-ab9f-b6abdf8ca362.jpg)
i know it is a thing as the nexus cwor has it working

**Comment by schofida** [comment]
Can you let me know what is not changing over? I was testing this earlier and the surrender scene played out.

**Comment by LABWAZHERE** [comment]
he doesn't say 'enough stop fighting' that i surrender part was from me talking to him afterwards

**Comment by schofida** [comment]
I will try testing this later tonight. I might have an idea.

**Comment by schofida** [comment]
Should be working now in latest version. I added the generic lines from the minor holds to any of the non-vanilla jarls in the major holds
