### ISSUE TITLE
idea for final stands

### ISSUE THREAD

**Issue by LABWAZHERE** [schofida/CWORR#78]
instead of meet with imperial preafect or stromcloak general you could do the general of solitude and windhelm as the person you meet with, for example this guy
![20230428100936_1](https://user-images.githubusercontent.com/128126252/235016099-2c6929b9-f426-4a3c-bfa5-4f42d913cf39.jpg)

**Comment by schofida** [comment]
Ugh.... this is a good idea. But will take a lot of work :(

The only reason why Rikke, Galmar, Ulfric and Tullius work is that they have their own special battle references. I would have to make a battle reference for each of the other Field CO's.

**Comment by schofida** [comment]
But its a really good idea

**Comment by LABWAZHERE** [comment]
damn, maybe you could leave it un fixed and ask if people are up to the task of making a patch like what i suggested with the escape scenes.

**Comment by LABWAZHERE** [comment]
oh i just realised you'd have to do this with all major holds and their generals

**Comment by LABWAZHERE** [comment]
update: looked at the files on creation kit, yeah i can see what you mean now

**Comment by LABWAZHERE** [comment]
addition to this idea is for offence sieges for capitals have the generals there as well 
because then when you get inside the keep and make the jarl surrender the new jarl says something along the lines of legate we have much to do

**Comment by schofida** [comment]
I only did this for the final stands. Doing for the rest of the holds will be too much work. But defending Solitude and Windhelm will have the completely unused Field CO's :) actually doing something now

**Comment by LABWAZHERE** [comment]
fair enough, i feel like only the other 3 major holds should of had that as the minor battles don't have dynamic change overs
defo gonna see if someone else will make a patch for them to do it, final sieges are now very epic

**Comment by ds-nscorp** [comment]
I added this to the backlog https://trello.com/c/p8EDLBKN.

This is a very good idea and one I want to implement (for all holds) but it will take a lot of time and will require a lot of testing.
