### ISSUE TITLE
Anarchy of War idea (Spanish inquisition overhaul)

### ISSUE THREAD

**Issue by LABWAZHERE** [schofida/CWORR#79]
okay now hear me out

after reading the cw scripts on creation kit, i think i know a better way to do this than spanish inquisition

we can do this by utilising the timers the generals have

Firstly mcm 
CWO logger
Anarchy mode  - this is where this part will be based move the troop garrisons and stuff to this tab
CWO Debug
CWO options
new options:
enable Anarchy (holds switching sides and hold defences) off by default
disable Chosen one (controls whether or not Markarth, Falkreath, Winterhold, Dawnstar, Morthal and Riften will randomly change hands before the battle of Whiterun). Whiterun enabled after battle of Whiterun.

troops mults
garrison mults
capital mults
siege mults

Options that can only be toggled once anarchy is enabled
Edit anarchy timer (edits the timer that the leaders use to time whether or not to activate defence missions)

Enable Preston Gravey mode 
(allows you to choose which hold you liberate next but will only work with tribune or legate and their Stormcloak equivalent) off by default

New features
fort switching - may not be possible to do if there isn't any actual dialogue

enable ocw style forts (allows forts to also change hands at random)

fort switch timer (controls how often it changes)

radiant fort missions given by commanders
(if i remember correctly there is radiant dialogue for fort capture/defence from other generals)

if this doesn't work just make the battle auto start when entering the forts area

town switching - 

towns can switch hands
battle will autostart when walking in towns area

mcm menu description is 

Enables the anarchy of war, it turns the war into a truely insane struggle for the control of skyrim

Anarchy mode will pause itself off when battle of Windhelm is activated and any enemy controlled forts/ towns will auto switch if a victory condition is reached if a failure condition is reached it will re enable itself

It will also shut off once season unending activates and will switch forts/towns back to the faction that currently controls the holds capital

additionally 
enable the strongest defence is a swift and decisive offence (enables a bonus to enemy stormcloak/imperial troops when the final siege is lost and a debuff to imperials/stormcloaks when they lose the final siege. (OCW has a thing where you can do a defence battle when both morthal and markarth are taken by the stormcloaks as the imperials and same with Windhelm as the stormcloaks)

**Comment by LABWAZHERE** [comment]
i'd make this myself but i know nothing about the cw quests and i don't think my pc could run creation engine

**Comment by LABWAZHERE** [comment]
update: after reviewing the cw scripts i realise most of this will be extremely hard, so maybe not

**Comment by LABWAZHERE** [comment]
i also realise this may pose a few issues
one of which being you not havinng time
the other of which do you make such a drastic change to apollodowns mod  or stay faithful to the original

if this concept isn't possible just make the hold switch timer editable

**Comment by LABWAZHERE** [comment]
if this is not doable for you, i'll learn how to mod and make a mod for it using cwo

**Comment by schofida** [comment]
Added to road map https://trello.com/c/FD9HMqL1/45-add-features-to-further-make-civil-war-more-dynamically-change-hold-hands
