### ISSUE TITLE
Remove war crimes (defectors and followers killing injured troops at camps)

### ISSUE THREAD

**Issue by LABWAZHERE** [schofida/CWORR#80]
war crimes bad, ples nerf

in all seriousness though please remove the enemy faction tag from the wounded soliders in the war camps, i don't like commiting war crimes and i don't want to execute my followers for doing so.

**Comment by schofida** [comment]
I noticed this and I was just working on this. 100% agree!

**Comment by LABWAZHERE** [comment]
i am dubbing the next update the  Geneva convention update

Changelog:

Added:
- The Geneva convention: 
During the the 4th era (4E 201) the Dragonborn forced the Aldmeri dominion, the Imperial empire, Hammerfell, Blackmarsh, Morrowind and the Stormcloak rebellion to sign a treaty at his mansion he named Geneva. This treaty named the Geneva convention ensured civilised warfare for years to come. 

Due to this followers and defectors are now familiar with the terms of the Geneva Convention. 

Removed:
- Warcrimes: 
Followers and defectors will no longer kill wounded soldiers in war camps and violate the terms of the Geneva Convention.  The Dragonborn is still exempt.

**Comment by LABWAZHERE** [comment]
from now on i am making my mission to give funny names to all the future updates

**Comment by schofida** [comment]
I am going to link to this issue on the Nexus page when CWO is ready. This is hilarious :)

This should be fixed now https://github.com/schofida/CWORR/releases/tag/v1.0.10a

I am going to close this but again, I will save it for posterity
