### ISSUE TITLE
joining the legion unable to be completed

### ISSUE THREAD

**Issue by LABWAZHERE** [schofida/CWORR#81]
the one fort that actually needs bandits active, doesnt have bandits active 
fort hraggstad doesn't have bandits enabled and as such can't be completed
no map marker either

**Comment by schofida** [comment]
Hmmm... I don't think that this is CWO. I made a fix to have remove bandits but not until after the Battle for Whiterun.

**Comment by LABWAZHERE** [comment]
i don't have any mods that edit forts, additionally there is no map marker

**Comment by LABWAZHERE** [comment]
yeah this may just be a map marker issue cause i found some bandits

**Comment by LABWAZHERE** [comment]
update killed all bandits, and nothing

**Comment by LABWAZHERE** [comment]
update markers have appeared, outside the fort
![20230428112030_1](https://user-images.githubusercontent.com/128126252/235031838-1ea5e165-0fec-4bd8-a7c9-69992aed356f.jpg)
![20230428112039_1](https://user-images.githubusercontent.com/128126252/235031839-9be575a5-c974-4498-a149-6c7a12b9ee7f.jpg)

**Comment by LABWAZHERE** [comment]
update they are citizens of dragons bridge?
![20230428112055_1](https://user-images.githubusercontent.com/128126252/235031815-7300a03a-1ef2-4132-8383-11c0095d0d04.jpg)

**Comment by LABWAZHERE** [comment]
update; can't fast travel cause "enemies nearby"
-

**Comment by LABWAZHERE** [comment]
hold up let me retest this this could be a me thing

**Comment by LABWAZHERE** [comment]
unable to reproduce, it was a me thing
