### ISSUE TITLE
courier idea

### ISSUE THREAD

**Issue by LABWAZHERE** [schofida/CWORR#82]
use these guys
![20230428113126_2](https://user-images.githubusercontent.com/128126252/235033072-3f458f21-462d-4054-9b15-565e33567973.jpg)

remember the mission where you have to go to candle hall and pretend to be the stormcloak courier, yeah 1 is that mission here and 2 use them as the couriers for the letters from commanders

**Comment by schofida** [comment]
Added to enhancements list.

Essentially I plan to incorporate this https://trello.com/c/4tCOSEk8/42-patch-for-https-wwwnexusmodscom-skyrimspecialedition-mods-81546
