### ISSUE TITLE
Better Defence of Whiterun (radiant) idea

### ISSUE THREAD

**Issue by LABWAZHERE** [schofida/CWORR#84]
instead of auto starting it should say meet with Legate Quentin Cipius

then he will say
![20230428122822_1](https://user-images.githubusercontent.com/128126252/235040033-ba711726-8b06-4f24-852d-5da7b7cdfad5.jpg)

**Comment by LABWAZHERE** [comment]
i doubt the Whiterun Stormcloak general has this dialogue but if he does then this would make a great addition

**Comment by schofida** [comment]
I believe that I already have this set up. Defense should not be auto-starting anymore for major cities. Can you try again?

**Comment by LABWAZHERE** [comment]
if that's the case it is only for defence missions given by courier and not started by spanish inquisition

**Comment by schofida** [comment]
I got this to work now for Spanish inquisiton. Leaving open because I think I can get this to work for minor city defense as well :)

**Comment by schofida** [comment]
You should have to report to the Field CO now for the defense of both major and minor cities now :) https://github.com/schofida/CWORR/releases/tag/v1.0.15a
