### ISSUE TITLE
Legate Fasendil disappears when rikke goes to riften camp

### ISSUE THREAD

**Issue by LABWAZHERE** [schofida/CWORR#86]
![20230428125417_1](https://user-images.githubusercontent.com/128126252/235043471-f0aa4364-40bc-42b9-be61-5a734633dc16.jpg)
this guy commits thanos snap when Rikke is at the camp, can he like not?

**Comment by schofida** [comment]
That's vanilla behavior. Buuuuttt... Maybe? I will add this to the enhancement list. The Field CO's are incredibly touchy so having them both in the same place will require a good amount of testing.

**Comment by LABWAZHERE** [comment]
fair but i think it makes sense to have both field cos there, also happens to the winterhold legate

**Comment by schofida** [comment]
https://trello.com/c/OvXsXrCC/41-dont-disable-camp-cos-when-rikke-galmar-travel-to-them

Added this to enhancement list. At present, this was done out of laziness I imagine by Bethesda. When Rikke/Galmar travel to the camps, they basically use the same sandbox packages by the legates, so they may frequently run into each other or combat each other to stay in the same spot. They also won't talk to each other etc.

**Comment by LABWAZHERE** [comment]
One thing that is interesting to point out is it doesn’t happen with all the commanders only some
