### ISSUE TITLE
winterhold quests not being given

### ISSUE THREAD

**Issue by LABWAZHERE** [schofida/CWORR#88]
![20230428214556_1](https://user-images.githubusercontent.com/128126252/235139443-2d5d079f-b921-4c26-a8ea-a095efe15409.jpg)
![20230428214558_1](https://user-images.githubusercontent.com/128126252/235139456-d62e9e44-1a1b-4adb-ae03-53120d25bcf4.jpg)
![20230428214559_1](https://user-images.githubusercontent.com/128126252/235139461-e97b398c-566b-49d4-8e34-be6f8169ba3b.jpg)
![20230428214600_1](https://user-images.githubusercontent.com/128126252/235139462-0d2ad135-5b08-4257-87f5-73dcd01ff16e.jpg)

**Comment by LABWAZHERE** [comment]
![20230428214755_1](https://user-images.githubusercontent.com/128126252/235139726-a6245c46-8e69-4207-ab4b-36265eff1ced.jpg)
this happened when i hit fix quest

**Comment by schofida** [comment]
This should be fixed https://github.com/schofida/CWORR/releases/tag/v1.0.10a. Did hitting 'Get Quest Unstuck' throw you in the air?

**Comment by LABWAZHERE** [comment]
> This should be fixed https://github.com/schofida/CWORR/releases/tag/v1.0.10a. Did hitting 'Get Quest Unstuck' throw you in the air?

no a dragon did, i was refering to the fact that i think the rescue mission wasn't properly being given

**Comment by ds-nscorp** [comment]
That is valid. Rescue quest for imperials happens in Winterhold. I just screwed up the dialogue record in the last updated

**Comment by LABWAZHERE** [comment]
update: got ... for a quest after completing kastav
