### ISSUE TITLE
rescue from fort kastav Hadvar

### ISSUE THREAD

**Issue by LABWAZHERE** [schofida/CWORR#90]
![20230429083844_1](https://user-images.githubusercontent.com/128126252/235265350-27d8235d-d556-4973-8f2e-e790ab34b813.jpg)
he doesnt actually go into the fort just here

**Comment by schofida** [comment]
I was not able to reproduce. Was this after you rescued the prisoners?

**Comment by LABWAZHERE** [comment]
Yes

**Comment by schofida** [comment]
This is unfortunately a vanilla bug then. He comes in fine for me but NPC AI packages can sometimes get hung up on their own feet for any reason.
