### ISSUE TITLE
Warcrimes still exist

### ISSUE THREAD

**Issue by LABWAZHERE** [schofida/CWORR#92]
looks like some people didn't read the Geneva convention properly

![20230429085928_1](https://user-images.githubusercontent.com/128126252/235267250-a3cb3997-dd27-4392-bd29-c2639c220a9f.jpg)
![20230429085940_1](https://user-images.githubusercontent.com/128126252/235267252-9e4f9595-0c22-4b3a-9265-678510080218.jpg)

just the end guy the other 2 injured are fine

lets teach these defectors a little thing i like to call the Nuremberg Trials

**Comment by LABWAZHERE** [comment]
when i revived the injured solider they didn't recommit the war crimes

i am calling the next update the 

Nuremberg Trials update

Changelog:
Removed:
- War crimes (again)

Added
- The Nuremberg trials
the people who commited the war crimes have been tried for their crimes and hung, the people you see in game are now aware of the consequences of commiting war crimes and will no longer commit them hopefully.

**Comment by schofida** [comment]
Finally fixed!!!

**Comment by LABWAZHERE** [comment]
Finally, took em long enough to learn, now time to tackle the next issue, nuclear warfare, let’s hope Ulfric doesn’t get too trigger happy
