### ISSUE TITLE
Winterhold camp is really scuffed

### ISSUE THREAD

**Issue by LABWAZHERE** [schofida/CWORR#93]
![20230429090746_1](https://user-images.githubusercontent.com/128126252/235267885-e5fc2f38-ba32-4919-a565-8eb6a097ad6c.jpg)

this is cursed

**Comment by schofida** [comment]
I could not reproduce this. Could be another mod??

**Comment by LABWAZHERE** [comment]
This could be a cc related thing as I believe I have encountered it in OCW and I know creation club edits some things, I’ll go to the place winterhold camp is meant to be and see if it is there when the camp isn’t

**Comment by LABWAZHERE** [comment]
okay yeah this is weird, the table only appears with the camp. idfk what is causing this, i have no mods that edit Winterhold period.

my only theories are
1. Creation club
2. Civil war aftermath
