### ISSUE TITLE
Regain Eastmarch given after losing the first time

### ISSUE THREAD

**Issue by LABWAZHERE** [schofida/CWORR#97]
talking to tulius will regive you the regain eastmarch option

additionally here is the mcm menu after losing but before speaking to tulius
![20230429101833_1](https://user-images.githubusercontent.com/128126252/235272544-34cd9f19-1fca-4a27-8cb8-7265abb001d1.jpg)

**Comment by LABWAZHERE** [comment]
update it says courier is on it's way so it is fine

**Comment by schofida** [comment]
This should be fixed in https://github.com/schofida/CWORR/releases/tag/v1.0.11a

**Comment by schofida** [comment]
Do note that you would need to lose again. I don't think that it would fix your save after this bug occurred
