### ISSUE TITLE
fort defence missions don't work

### ISSUE THREAD

**Issue by LABWAZHERE** [schofida/CWORR#98]
![20230429102604_1](https://user-images.githubusercontent.com/128126252/235272932-da4349ba-958f-4517-abea-7e261e17c516.jpg)

**Comment by LABWAZHERE** [comment]
on another note it may be worth looking into the serious fort commanders mod
https://www.nexusmods.com/skyrimspecialedition/mods/81541

**Comment by LABWAZHERE** [comment]
works

**Comment by schofida** [comment]
So I am pretty sure that this was related to issue #97. This was a good catch :)

> on another note it may be worth looking into the serious fort commanders mod
https://github.com/schofida/CWORR/releases/tag/SCWOFC

Compatibility patch. I have not tested but feel free to give it a try.
