### ISSUE TITLE
Tulius has the wrong sword

### ISSUE THREAD

**Issue by LABWAZHERE** [schofida/CWORR#99]
he usually wields an Elven sword
![20230429103727_1](https://user-images.githubusercontent.com/128126252/235273476-a5e1f0a0-5bbb-4a0f-a9a8-25f98d6f2372.jpg)
not an imperial one

**Comment by schofida** [comment]
That might be from another mod. In vanilla he wields an imperial sword. CWO does not change that

**Comment by LABWAZHERE** [comment]
then open civil war must be wrong, in that mod tulius has a Glass sword and gives you "his sword" to kill ulfric which is the glass sword he gives you

**Comment by ds-nscorp** [comment]
Hmm. Well it's a 'Take my sword. I've sharpened it for the occasion.' My head-cannon has it where he has another sword stowed away to kill Ulfric, like a ceremonial sword or something. In CWO, when he gives you 'his sword' you get Stormblade, a Glass Sword with a lightning enchantment. It's stupid strong.

**Comment by LABWAZHERE** [comment]
Fair enough, i'll agree with that too and the name "Stormblade" really rubs it in Ulfrics face especially if the Dragonborn kills Ulfric after betraying him

**Comment by LABWAZHERE** [comment]
oh also i meant glass
